<?php
namespace App\Services;
use App\Models\{Employe,RhContrat};use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class RhContratService{
 public function __construct(private RhContractNumberService $numeros){}
 public function creer(array $d,int $auteur):RhContrat{return DB::transaction(function()use($d,$auteur){$e=Employe::lockForUpdate()->findOrFail($d['employe_id']);if($d['statut']==='Actif')$this->verifierChevauchement($e,$d);$d['numero']=$this->numeros->contrat($e->entreprise_id,(int)date('Y',strtotime($d['date_debut'])));return RhContrat::create($d+['entreprise_id'=>$e->entreprise_id,'user_id'=>$e->user_id,'departement_id'=>$e->departement_id,'service_id'=>$d['service_id']??$e->service_id,'fonction_id'=>$e->fonction_id,'cree_par'=>$auteur]);});}
 public function soumettre(RhContrat $c,int $auteur):void{if($c->statut!=='Brouillon')throw ValidationException::withMessages(['statut'=>'Seul un brouillon peut être soumis.']);$c->update(['statut'=>'En attente de validation','modifie_par'=>$auteur]);}
 public function valider(RhContrat $c,int $validateur):void{if(!in_array($c->statut,['Brouillon','En attente de validation','À vérifier'],true))throw ValidationException::withMessages(['statut'=>'Ce contrat ne peut pas être validé.']);if($c->cree_par===$validateur)throw ValidationException::withMessages(['statut'=>'Le créateur ne peut pas valider son propre contrat.']);$c->update(['statut'=>'Validé','valide_par'=>$validateur,'valide_le'=>now(),'modifie_par'=>$validateur]);}
 public function activer(RhContrat $c,int $auteur):void{if($c->statut!=='Validé')throw ValidationException::withMessages(['statut'=>'Le contrat doit d’abord être validé.']);$this->verifierChevauchement($c->employe,$c->toArray(),$c->id);$c->update(['statut'=>'Actif','modifie_par'=>$auteur]);}
 public function verifierChevauchement(Employe $e,array $d,?int $ignore=null):void{$q=RhContrat::where('employe_id',$e->id)->where('statut','Actif')->when($ignore,fn($q)=>$q->whereKeyNot($ignore))->whereDate('date_debut','<=',$d['date_fin']??'9999-12-31')->where(fn($q)=>$q->whereNull('date_fin')->orWhereDate('date_fin','>=',$d['date_debut']));if($q->exists())throw ValidationException::withMessages(['date_debut'=>'Un contrat actif chevauche déjà cette période.']);}
}
