<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>@page{margin:28px 34px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:11px}.header{border-bottom:3px solid #167c80;padding-bottom:14px;margin-bottom:18px}.logo{max-height:60px;max-width:120px;float:right}h1{font-size:22px;color:#0f2744;margin:0}h2{font-size:13px;color:#167c80;margin:20px 0 8px}.muted{color:#667085}.grid{width:100%;border-collapse:collapse}.grid td{width:50%;vertical-align:top;padding:3px 8px 3px 0}.pay{width:100%;border-collapse:collapse;margin-top:8px}.pay th{background:#0f2744;color:white;padding:8px;text-align:left}.pay td{padding:8px;border-bottom:1px solid #dbe2ea}.amount{text-align:right}.total td{font-weight:bold;background:#eef7f7;border-top:2px solid #167c80}.net{margin-top:16px;background:#167c80;color:white;padding:14px;font-size:16px;font-weight:bold}.right{float:right}.footer{position:fixed;bottom:0;left:0;right:0;border-top:1px solid #ddd;padding-top:7px;color:#667085;font-size:9px}.draft{position:fixed;top:42%;left:14%;transform:rotate(-30deg);font-size:70px;color:rgba(190,0,0,.12);font-weight:bold}</style></head><body>
@if(!in_array($paie->statut,['Validée','Payée'],true))<div class="draft">BROUILLON</div>@endif
<div class="header">@if($entreprise->logo && file_exists(public_path('storage/'.$entreprise->logo)))<img class="logo" src="{{public_path('storage/'.$entreprise->logo)}}">@endif<h1>BULLETIN DE PAIE</h1><strong>{{$entreprise->nom_entreprise}}</strong><div class="muted">{{$entreprise->adresse}} · {{$entreprise->telephone}}</div>@if($paie->reference_paiement)<div style="margin-top:8px"><strong>Référence : {{$paie->reference_paiement}}</strong></div>@endif</div>
<table class="grid"><tr><td><strong>Employé :</strong> {{$paie->employe->nom}} {{$paie->employe->postnom}} {{$paie->employe->prenom}}</td><td><strong>Matricule :</strong> {{$paie->employe->matricule}}</td></tr><tr><td><strong>Département :</strong> {{$paie->employe->departement?->designation??'—'}}</td><td><strong>Fonction :</strong> {{$paie->employe->fonction?->designation??'—'}}</td></tr><tr><td><strong>Période :</strong> {{str_pad($paie->mois,2,'0',STR_PAD_LEFT)}}/{{$paie->annee}}</td><td><strong>Devise :</strong> {{$paie->monnaie}}</td></tr></table>
<h2>DÉTAIL DE LA RÉMUNÉRATION</h2><p class="muted">Retenues appliquées : <strong>{{$paie->appliquer_retenues?'Oui':'Non'}}</strong></p><table class="pay"><thead><tr><th>Rubrique</th><th class="amount">Gains</th><th class="amount">Retenues</th></tr></thead><tbody><tr><td>Salaire de base</td><td class="amount">{{number_format($paie->salaire_base,2,',',' ')}}</td><td></td></tr>
@if($paie->lignes->isNotEmpty())
@foreach($paie->lignes as $ligne)<tr><td>{{$ligne->libelle}} @if($ligne->taux)<small>({{number_format($ligne->taux,2,',',' ')}} %)</small>@endif</td><td class="amount">{{$ligne->type==='Gain'?number_format($ligne->montant,2,',',' '):''}}</td><td class="amount">{{$ligne->type!=='Gain'?number_format($ligne->montant,2,',',' '):''}}</td></tr>@endforeach
@else
@if((float)$paie->primes>0)<tr><td>Primes et indemnités</td><td class="amount">{{number_format($paie->primes,2,',',' ')}}</td><td></td></tr>@endif
@if((float)$paie->retenues>0)<tr><td>Autres retenues</td><td></td><td class="amount">{{number_format($paie->retenues,2,',',' ')}}</td></tr>@endif
@endif
<tr class="total"><td>TOTAUX</td><td class="amount">{{number_format($paie->calculerTotalGains(),2,',',' ')}}</td><td class="amount">{{number_format((float)$paie->retenues+(float)$paie->total_taxes+(float)$paie->total_cotisations,2,',',' ')}}</td></tr></tbody></table>
<div class="net">NET À PAYER <span class="right">{{number_format($paie->net,2,',',' ')}} {{$paie->monnaie}}</span></div>
<h2>INFORMATIONS DE PAIEMENT</h2><table class="pay"><tbody><tr><td><strong>Statut</strong></td><td>{{$paie->statut}}</td></tr><tr><td><strong>Date de paiement</strong></td><td>{{$paie->date_paiement?->format('d/m/Y')??'—'}}</td></tr><tr><td><strong>Mode de paiement</strong></td><td>{{$paie->mode_paiement??'—'}}</td></tr><tr><td><strong>Référence automatique</strong></td><td><strong>{{$paie->reference_paiement??'—'}}</strong></td></tr></tbody></table>
<table style="width:100%;margin-top:38px"><tr><td style="width:50%;text-align:center">Signature de l’employé<br><br><br>____________________________</td><td style="width:50%;text-align:center">Responsable habilité<br><br><br>____________________________</td></tr></table>
<div class="footer">Document confidentiel — Généré le {{now()->format('d/m/Y à H:i')}} par {{auth()->user()->nom}} {{auth()->user()->prenom}}.</div></body></html>
