@extends('layouts.app')
@section('title','Employés')
@section('module-sidebar') @include('ressources_humaines._sidebar') @endsection
@section('content')
<div class="container-fluid py-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="fw-bold mb-1">Employés</h2><p class="text-muted mb-0">Dossiers du personnel indépendants des comptes de connexion.</p></div>@can('createEmployees')<a class="btn btn-primary" href="{{ route('parametres.rh.employes.create') }}"><i class="bi bi-person-plus"></i> Nouvel employé</a>@endcan</div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<form class="card card-body border-0 shadow-sm mb-3" method="GET"><div class="row g-2"><div class="col-lg-4"><input class="form-control" name="q" value="{{request('q')}}" placeholder="Matricule, nom, téléphone ou e-mail"></div><div class="col-md-3 col-lg-2"><select class="form-select" name="departement_id"><option value="">Tous départements</option>@foreach($departements as $d)<option value="{{$d->id}}" @selected(request('departement_id')==$d->id)>{{$d->designation}}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><select class="form-select" name="fonction_id"><option value="">Toutes fonctions</option>@foreach($fonctions as $f)<option value="{{$f->id}}" @selected(request('fonction_id')==$f->id)>{{$f->designation}}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><select class="form-select" name="statut"><option value="">Tous statuts</option>@foreach(['Brouillon','Actif','En congé','Suspendu','Sorti','Retraité','Archivé'] as $s)<option @selected(request('statut')===$s)>{{$s}}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><button class="btn btn-outline-primary w-100">Filtrer</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Matricule</th><th>Employé</th><th>Organisation</th><th>Contact</th><th>Statut</th><th></th></tr></thead><tbody>@forelse($employes as $e)<tr><td class="fw-semibold">{{$e->matricule}}</td><td>{{$e->nom}} {{$e->postnom}} {{$e->prenom}}</td><td>{{$e->departement?->designation??'—'}}<small class="d-block text-muted">{{$e->fonction?->designation??'—'}}</small></td><td>{{$e->telephone??'—'}}<small class="d-block text-muted">{{$e->email}}</small></td><td><span class="badge bg-{{$e->statut==='Actif'?'success':'secondary'}}">{{$e->statut}}</span></td><td><a class="btn btn-sm btn-outline-primary" href="{{route('parametres.rh.employes.show',$e)}}">Voir</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">Aucun employé ne correspond aux filtres.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{$employes->links()}}</div></div>
@endsection
