@extends('layouts.app')
@section('title', 'Exécution budgétaire')
@section('module-sidebar') @include('budgets._sidebar') @endsection
@section('content')
@include('budgets._styles')
<div class="container-fluid py-3 budget-dashboard">@include('budgets._heading',['eyebrow'=>'Analyse','heading'=>'Exécution budgétaire','description'=>'Comparez les prévisions, les réalisations et les soldes disponibles.','icon'=>'bar-chart-line'])
@include('budgets._report_actions', ['rapport' => 'execution'])
<div class="row g-3 mb-4">@foreach([['Prévision',$budgetSummary['initial'],'primary'],['Réalisation',$budgetSummary['realise'],'success'],['Disponible',$budgetSummary['disponible'],$budgetSummary['disponible']<0?'danger':'info']] as [$label,$value,$color])<div class="col-md-4"><div class="budget-kpi"><span class="budget-kpi-icon bg-{{ $color }} bg-opacity-10 text-{{ $color }}"><i class="bi bi-graph-up"></i></span><div><small>{{ $label }}</small><strong>{{ number_format($value,2,',',' ') }} CDF</strong></div></div></div>@endforeach</div>
<section class="card border-0 shadow-sm"><div class="card-body p-4"><h5>Taux d’exécution global</h5>@php($taux=min(max($budgetSummary['taux_execution'],0),100))<div class="d-flex justify-content-between mt-4"><span>Progression</span><strong>{{ number_format($budgetSummary['taux_execution'],1,',',' ') }} %</strong></div><div class="progress budget-progress mt-2"><div class="progress-bar" style="width:{{ $taux }}%"></div></div></div></section>
<section class="card border-0 shadow-sm mt-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Rubrique</th><th>Nature</th><th>Période</th><th>Compte</th><th class="text-end">Initial</th><th class="text-end">Révisé</th><th class="text-end">Engagé</th><th class="text-end">Réalisé comptable</th><th class="text-end">Disponible / Reste</th><th class="text-end">Écart</th><th class="text-end">Taux</th></tr></thead><tbody>@forelse($lignesBudgetaires as $ligne)<tr><td class="fw-semibold">{{ $ligne->rubrique }}</td><td><span class="badge bg-{{ $ligne->nature_budgetaire==='RECETTE'?'success':'danger' }}">{{ $ligne->nature_budgetaire }}</span></td><td class="text-nowrap">{{ $ligne->date_debut?->format('d/m/Y') }} – {{ $ligne->date_fin?->format('d/m/Y') }}</td><td>{{ $ligne->compte?->compte }} — {{ $ligne->compte?->designation }}</td><td class="text-end">{{ number_format($ligne->prevision_initiale,2,',',' ') }}</td><td class="text-end">{{ number_format($ligne->budget_revise,2,',',' ') }}</td><td class="text-end">{{ number_format($ligne->nature_budgetaire==='DEPENSE'?$ligne->engagements_actifs:0,2,',',' ') }}</td><td class="text-end">{{ number_format($ligne->realise_comptable,2,',',' ') }}</td><td class="text-end fw-bold">{{ number_format($ligne->nature_budgetaire==='DEPENSE'?$ligne->disponible_comptable:$ligne->reste_a_realiser,2,',',' ') }}</td><td class="text-end">{{ number_format($ligne->ecart_comptable,2,',',' ') }}</td><td class="text-end">{{ number_format($ligne->taux_execution_comptable,1,',',' ') }} %</td></tr>@empty<tr><td colspan="11" class="text-center text-muted py-5">Aucune ligne budgétaire validée.</td></tr>@endforelse</tbody></table></div></section>
</div>@endsection
