@extends('layouts.app')
@section('title','Révisions et transferts')
@section('module-sidebar') @include('budgets._sidebar') @endsection
@section('content') @include('budgets._styles')
<div class="container-fluid py-3 budget-dashboard">@include('budgets._heading',['eyebrow'=>'Ajustements','heading'=>'Révisions et transferts','description'=>'Ajustez les crédits sans écraser leur historique.','icon'=>'shuffle'])
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3"><div class="col-lg-6">@can('reviseBudget')<section class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h5>Réviser une ligne</h5><form method="POST" action="{{ $lignesBudgetaires->isNotEmpty()?route('parametres.budgets.lignes.revision',$lignesBudgetaires->first()):'#' }}" id="revisionForm" class="row g-3">@csrf<div class="col-12"><label class="form-label">Ligne</label><select class="form-select" id="revisionLine" required>@foreach($lignesBudgetaires as $l)<option data-action="{{ route('parametres.budgets.lignes.revision',$l) }}">{{ $l->code }} — {{ $l->rubrique }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Sens</label><select name="sens" class="form-select"><option value="positive">Positive</option><option value="negative">Négative</option></select></div><div class="col-md-7"><label class="form-label">Montant</label><input name="montant" type="number" min="0.01" step="0.01" class="form-control" required></div><div class="col-12"><label class="form-label">Motif</label><textarea name="motif" minlength="10" class="form-control" required></textarea></div><div class="col-12 text-end"><button class="btn btn-primary" @disabled($lignesBudgetaires->isEmpty())>Enregistrer la révision</button></div></form></div></section>@endcan</div>
<div class="col-lg-6">@can('transferBudget')<section class="card border-0 shadow-sm h-100"><div class="card-body p-4"><h5>Transférer des crédits</h5><form method="POST" action="{{ route('parametres.budgets.transferts.store') }}" class="row g-3">@csrf<div class="col-12"><label class="form-label">Ligne source</label><select name="source_id" class="form-select" required>@foreach($lignesBudgetaires as $l)<option value="{{ $l->id }}">{{ $l->code }} — disponible {{ number_format($l->disponible,2,',',' ') }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Ligne destination</label><select name="destination_id" class="form-select" required>@foreach($lignesBudgetaires as $l)<option value="{{ $l->id }}">{{ $l->code }} — {{ $l->rubrique }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Montant</label><input name="montant" type="number" min="0.01" step="0.01" class="form-control" required></div><div class="col-12"><label class="form-label">Motif</label><textarea name="motif" minlength="10" class="form-control" required></textarea></div><div class="col-12 text-end"><button class="btn btn-primary">Effectuer le transfert</button></div></form></div></section>@endcan</div></div></div>
@endsection
@section('scripts')<script>document.getElementById('revisionLine')?.addEventListener('change',function(){document.getElementById('revisionForm').action=this.selectedOptions[0].dataset.action;});</script>@endsection
