@extends('layouts.app')
@section('title','Rubriques budgétaires')
@section('module-sidebar') @include('budgets._sidebar') @endsection
@section('content') @include('budgets._styles')
<div class="container-fluid py-3 budget-dashboard">@include('budgets._heading',['eyebrow'=>'Référentiel','heading'=>'Rubriques budgétaires','description'=>'Chaque rubrique est liée à un compte comptable et possède une nature.','icon'=>'tags'])
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@can('manageBudgetLines')<section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form method="POST" action="{{ route('parametres.budgets.rubriques.store') }}" class="row g-3">@csrf<div class="col-md-4"><label class="form-label">Désignation</label><input name="designation" value="{{ old('designation') }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Nature</label><select name="nature" class="form-select" required><option>DEPENSE</option><option>RECETTE</option></select></div><div class="col-md-6"><label class="form-label">Compte</label><select name="liste_des_comptes_id" class="form-select" required><option value="">Sélectionner</option>@foreach($comptes as $c)<option value="{{ $c->id }}">{{ $c->compte }} — {{ $c->designation }} ({{ $c->nature }})</option>@endforeach</select></div><div class="col-12"><label class="form-label">Description</label><input name="description" class="form-control"></div><div class="col-12 text-end"><button class="btn btn-primary">Créer la rubrique</button></div></form></div></section>@endcan
<section class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Désignation</th><th>Nature</th><th>Compte</th><th>État</th><th>Action</th></tr></thead><tbody>@forelse($rubriquesBudgetaires as $r)<tr><td>{{ $r->designation }}</td><td><span class="badge bg-{{ $r->nature==='RECETTE'?'success':'danger' }}">{{ $r->nature }}</span></td><td>{{ $r->compte?->compte }} — {{ $r->compte?->designation }}</td><td>{{ $r->actif?'Active':'Inactive' }}</td><td>@can('manageBudgetLines')<form method="POST" action="{{ route('parametres.budgets.rubriques.update',$r) }}" class="d-flex gap-1">@csrf @method('PATCH')<input type="hidden" name="designation" value="{{ $r->designation }}"><input type="hidden" name="actif" value="{{ $r->actif?0:1 }}"><button class="btn btn-sm btn-outline-{{ $r->actif?'warning':'success' }}">{{ $r->actif?'Désactiver':'Activer' }}</button></form>@endcan</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-5">Aucune rubrique.</td></tr>@endforelse</tbody></table></div></section></div>
@endsection
