@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><span class="badge bg-danger mb-2">Document supprimé</span><h3 class="mb-0">{{ $document->numero ?? $document->reference ?? $document->piece ?? class_basename($document) }}</h3></div><a href="{{ route('corbeille.index') }}" class="btn btn-outline-secondary">Retour à la corbeille</a></div>
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="row g-4"><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Données conservées</div><div class="card-body"><dl class="row mb-0">@foreach($document->attributesToArray() as $key=>$value)<dt class="col-sm-4 text-muted">{{ str_replace('_',' ',$key) }}</dt><dd class="col-sm-8 text-break">{{ is_array($value) ? json_encode($value, JSON_UNESCAPED_UNICODE) : ($value ?? '—') }}</dd>@endforeach</dl></div></div></div>
    <div class="col-lg-5"><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-bold">Actions sécurisées</div><div class="card-body">
        <form method="POST" action="{{ route('corbeille.restore', [$module,$document->id]) }}" class="mb-3">@csrf<label class="form-check"><input class="form-check-input" type="checkbox" name="cascade" value="1"><span class="form-check-label">Restaurer aussi les documents liés supprimés</span></label><button class="btn btn-success w-100 mt-3"><i class="bi bi-arrow-counterclockwise me-1"></i>Restaurer</button></form>
        <hr><form method="POST" action="{{ route('corbeille.force-delete', [$module,$document->id]) }}">@csrf @method('DELETE')<label class="form-label">Motif de suppression définitive</label><textarea name="motif" minlength="10" maxlength="1000" required class="form-control mb-2"></textarea><label class="form-label">Saisissez : <strong>SUPPRIMER DÉFINITIVEMENT</strong></label><input name="phrase_confirmation" required class="form-control mb-2"><label class="form-check mb-3"><input type="checkbox" name="confirmation_comptable" value="1" required class="form-check-input"><span class="form-check-label">Je confirme cette suppression irréversible.</span></label><button class="btn btn-danger w-100">Supprimer définitivement</button></form>
    </div></div></div></div>
    <div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white fw-bold">Journal d’audit</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Action</th><th>Utilisateur</th><th>Motif</th><th>Dépendances</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ $audit->created_at?->format('d/m/Y H:i:s') }}</td><td>{{ $audit->action }}</td><td>{{ $audit->user?->email ?? 'Système' }}</td><td>{{ $audit->motif ?: '—' }}</td><td><code>{{ json_encode($audit->dependances, JSON_UNESCAPED_UNICODE) }}</code></td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Aucun audit.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
