<h4 class="mb-3">Historique des présences</h4>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><form method="GET" class="row g-2 align-items-end">
    <div class="col-md-2"><label class="form-label small">Du</label><input type="date" name="date_debut" value="{{request('date_debut')}}" class="form-control"></div>
    <div class="col-md-2"><label class="form-label small">Au</label><input type="date" name="date_fin" value="{{request('date_fin')}}" class="form-control"></div>
    <div class="col-md-2"><label class="form-label small">Employé</label><select name="employe_id" class="form-select"><option value="">Tous</option>@foreach($employes as $employe)<option value="{{$employe->id}}" @selected(request('employe_id')==$employe->id)>{{$employe->matricule}} — {{$employe->nom}} {{$employe->prenom}}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label small">Département</label><select name="departement_id" class="form-select"><option value="">Tous</option>@foreach($departements as $departement)<option value="{{$departement->id}}" @selected(request('departement_id')==$departement->id)>{{$departement->designation}}</option>@endforeach</select></div>
    @if($sites->isNotEmpty())<div class="col-md-2"><label class="form-label small">Site</label><select name="site_id" class="form-select"><option value="">Tous</option>@foreach($sites as $site)<option value="{{$site->id}}" @selected(request('site_id')==$site->id)>{{$site->nom}}</option>@endforeach</select></div>@endif
    <div class="col-md-2"><label class="form-label small">Statut</label><select name="statut" class="form-select"><option value="">Tous</option>@foreach(['Présent','Retard','Absent','Absence justifiée','Absence non justifiée','Congé','Maladie','Mission','Permission','Repos','Jour férié','Télétravail'] as $statut)<option @selected(request('statut')===$statut)>{{$statut}}</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label small">Méthode</label><select name="methode_pointage" class="form-select"><option value="">Toutes</option><option @selected(request('methode_pointage')==='QR Code')>QR Code</option><option @selected(request('methode_pointage')==='Manuel')>Manuel</option></select></div>
    <div class="col-md-2 d-flex gap-2"><button class="btn btn-primary">Filtrer</button><a href="{{route('parametres.rh.presences')}}" class="btn btn-outline-secondary">Effacer</a></div>
</form></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Date</th><th>Employé</th><th>Arrivée</th><th>Départ</th><th class="text-end">Retard</th><th class="text-end">Départ anticipé</th><th>Statut</th><th>Méthode</th><th></th></tr></thead><tbody>
@forelse($elements as $e)<tr><td>{{$e->date->format('d/m/Y')}}</td><td>{{$e->employe?->nom}} {{$e->employe?->prenom}}<small class="d-block text-muted">{{$e->employe?->matricule}}</small></td><td>{{$e->heure_arrivee ? substr($e->heure_arrivee,0,5) : '—'}}</td><td>{{$e->heure_depart ? substr($e->heure_depart,0,5) : '—'}}</td><td class="text-end">{{$e->retard_minutes}} min</td><td class="text-end">{{$e->depart_anticipe_minutes}} min</td><td>@if($e->heure_arrivee && !$e->heure_depart)<span class="badge bg-info text-dark">Présence incomplète</span>@else<span class="badge bg-{{$e->statut==='Absent'?'danger':($e->retard_minutes>0||$e->depart_anticipe_minutes>0?'warning':'success')}}">{{$e->statut}}</span>@endif</td><td><span class="badge bg-{{$e->methode_pointage==='QR Code'?'primary':'secondary'}}">{{$e->methode_pointage ?? 'Manuel'}}</span></td><td class="text-nowrap">@can('manageAttendance')@if($e->statut_validation==='Validé')<button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#correction-presence-{{$e->id}}" title="Correction motivée"><i class="bi bi-pencil"></i></button>@endif @endcan @include('ressources_humaines._delete',['type'=>'presences','id'=>$e->id])</td></tr>
@empty<tr><td colspan="9" class="text-center py-5 text-muted">Aucune présence enregistrée.</td></tr>@endforelse
</tbody></table></div></div>
@can('manageAttendance')
@foreach($elements as $e)@if($e->statut_validation==='Validé')<div class="modal fade" id="correction-presence-{{$e->id}}" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{route('parametres.rh.presences.correct',$e)}}" class="modal-content">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Corriger le pointage — {{$e->employe?->nom}} {{$e->employe?->prenom}}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-6"><label class="form-label">Arrivée</label><input type="time" name="heure_arrivee" value="{{substr((string)$e->heure_arrivee,0,5)}}" class="form-control"></div><div class="col-6"><label class="form-label">Départ</label><input type="time" name="heure_depart" value="{{substr((string)$e->heure_depart,0,5)}}" class="form-control"></div><input type="hidden" name="statut" value="{{$e->statut}}"><div class="col-12"><label class="form-label">Motif obligatoire</label><textarea name="motif_correction" class="form-control" required minlength="3"></textarea><div class="form-text">L’ancienne et la nouvelle valeur ainsi que votre identité seront journalisées.</div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Annuler</button><button class="btn btn-primary">Enregistrer la correction</button></div></form></div></div>@endif @endforeach
@endcan
