@extends('layouts.app')
@section('title',ucfirst($module))
@section('module-sidebar') @include('ressources_humaines._sidebar') @endsection
@section('content')
@php($titres=['contrats'=>'Contrats','presences'=>'Présences','conges'=>'Congés','paie'=>'Paie','evaluations'=>'Évaluations'])
<div class="container-fluid py-4"><h2 class="fw-bold">{{ $titres[$module] }}</h2><p class="text-muted">Gestion opérationnelle des {{ strtolower($titres[$module]) }}.</p>@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if($module==='presences' && isset($statsPresence))<div class="row g-3 mb-4">@foreach([['Présences',$statsPresence['presences'],'success'],['Absences',$statsPresence['absences'],'danger'],['Retards',$statsPresence['retards'],'warning'],['Heures supplémentaires',number_format($statsPresence['heures_supplementaires'],2,',',' '),'info']] as [$label,$value,$color])<div class="col-6 col-lg-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">{{$label}}</small><div class="fs-3 fw-bold text-{{$color}}">{{$value}}</div></div></div></div>@endforeach</div>@endif
@php($peutSaisir = match($module){'contrats'=>auth()->user()->can('manageContracts'),'presences'=>auth()->user()->can('manageAttendance'),'conges'=>auth()->user()->can('requestLeave'),'paie'=>auth()->user()->can('createPayroll'),'evaluations'=>auth()->user()->can('manageEvaluations'),default=>false})
@if($peutSaisir)<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form method="POST" action="{{ route('parametres.rh.'.$module.'.store') }}" class="row g-3">@csrf
@php($utiliseEmploye = in_array($module,['contrats','presences'],true))
<div class="col-md-4"><label class="form-label">Employé</label><select name="{{ $utiliseEmploye?'employe_id':'user_id' }}" class="form-select" required><option value="">Sélectionner</option>@foreach($employes as $e)@php($horairePresence=$module==='presences'?($e->horaire??($horaireDefaut??null)):null)<option value="{{ $utiliseEmploye?$e->id:$e->user_id }}" @disabled(!$utiliseEmploye&&!$e->user_id) @if($horairePresence) data-debut="{{substr($horairePresence->heure_debut,0,5)}}" data-fin="{{substr($horairePresence->heure_fin,0,5)}}" data-pause="{{$horairePresence->pause_minutes}}" data-heures="{{$horairePresence->heures_normales}}" data-tolerance="{{$horairePresence->tolerance_retard_minutes}}" @endif>{{ $e->matricule }} — {{ $e->nom }} {{ $e->prenom }}</option>@endforeach</select></div>
@if($module==='contrats')<div class="col-md-2"><label class="form-label">Numéro</label><input name="numero" class="form-control" required></div><div class="col-md-2"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['CDI','CDD','Stage','Essai','Consultance','Journalier','Autre'] as $v)<option>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Début</label><input type="date" name="date_debut" class="form-control" required></div><div class="col-md-2"><label class="form-label">Fin</label><input type="date" name="date_fin" class="form-control"></div><div class="col-md-2"><label class="form-label">Essai (jours)</label><input type="number" min="0" name="periode_essai_jours" value="0" class="form-control"></div><div class="col-md-2"><label class="form-label">Heures/semaine</label><input type="number" min="1" max="168" step=".5" name="heures_hebdomadaires" value="40" class="form-control" required></div><div class="col-md-3"><label class="form-label">Salaire de base</label><input type="number" min="0" step=".01" name="salaire_base" class="form-control" required></div><div class="col-md-2"><label class="form-label">Devise</label><select name="devise" class="form-select"><option>CDF</option><option>USD</option></select></div><div class="col-md-3"><label class="form-label">Lieu de travail</label><input name="lieu_travail" class="form-control"></div><div class="col-md-3"><label class="form-label">Statut</label><select name="statut" class="form-select">@foreach(['Brouillon','Actif','Suspendu','Terminé','Résilié'] as $v)<option>{{ $v }}</option>@endforeach</select></div>
@elseif($module==='presences')<div class="col-md-2"><label class="form-label">Date</label><input type="date" name="date" value="{{now()->toDateString()}}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Arrivée</label><input type="time" name="heure_arrivee" class="form-control"></div><div class="col-md-2"><label class="form-label">Début pause</label><input type="time" name="debut_pause" class="form-control"></div><div class="col-md-2"><label class="form-label">Fin pause</label><input type="time" name="fin_pause" class="form-control"></div><div class="col-md-2"><label class="form-label">Départ</label><input type="time" name="heure_depart" class="form-control"></div><div class="col-md-2"><label class="form-label">Statut</label><select name="statut" class="form-select">@foreach(['Présent','Absent','Retard','Mission','Télétravail','Congé','Jour férié'] as $v)<option>{{ $v }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Observation / justification</label><input name="observation" class="form-control"></div><div class="col-12"><div id="presence-calcul" class="row g-2 p-3 bg-light rounded"><div class="col-6 col-lg-3"><small class="text-muted">Travaillées</small><div class="fw-bold" data-resultat="travaillees">0,00 h</div></div><div class="col-6 col-lg-3"><small class="text-muted">Retard</small><div class="fw-bold" data-resultat="retard">0 min</div></div><div class="col-6 col-lg-3"><small class="text-muted">Départ anticipé</small><div class="fw-bold" data-resultat="depart">0 min</div></div><div class="col-6 col-lg-3"><small class="text-muted">H. suppl. automatique</small><div class="fw-bold" data-resultat="supplementaires">0,00 h</div></div></div></div>
@elseif($module==='conges')<div class="col-md-3"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['Annuel','Maladie','Maternité','Paternité','Exceptionnel'] as $v)<option>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Début</label><input type="date" name="date_debut" class="form-control" required></div><div class="col-md-2"><label class="form-label">Fin</label><input type="date" name="date_fin" class="form-control" required></div>
@elseif($module==='paie')<div class="col-md-2"><label class="form-label">Année</label><input type="number" name="annee" value="{{now()->year}}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Mois</label><input type="number" min="1" max="12" name="mois" value="{{now()->month}}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Salaire de base</label><input type="number" min="0" step=".01" name="salaire_base" class="form-control" required></div><div class="col-md-2"><label class="form-label">Monnaie</label><select name="monnaie" class="form-select"><option>CDF</option><option>USD</option></select></div><div class="col-md-2"><label class="form-label">Statut</label><select name="statut" class="form-select"><option>Brouillon</option><option>Validée</option><option>Payée</option></select></div><div class="col-md-2"><label class="form-label">Date de paiement</label><input type="date" name="date_paiement" class="form-control"></div><div class="col-md-3"><label class="form-label">Mode de paiement</label><select name="mode_paiement" class="form-select"><option value="">Sélectionner</option><option>Cash</option><option>Mobile money</option><option>Virement bancaire</option></select></div><div class="col-md-3"><label class="form-label">Référence</label><input class="form-control" value="Générée automatiquement" disabled></div>@foreach($rubriques as $rubrique)<div class="col-md-3"><label class="form-label">{{$rubrique->libelle}} <span class="badge bg-light text-dark">{{$rubrique->type}}</span></label><input type="number" min="0" step=".01" name="rubriques[{{$rubrique->id}}]" value="{{old('rubriques.'.$rubrique->id,$rubrique->mode_calcul==='Montant fixe'?$rubrique->valeur:0)}}" class="form-control"><div class="form-text">{{$rubrique->mode_calcul}}{{$rubrique->mode_calcul==='Taux'?' : '.$rubrique->valeur.' %':''}}</div></div>@endforeach @can('manageHRSettings')<div class="col-12"><a href="{{route('parametres.rh.settings')}}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-sliders"></i> Paramètres RH et paie</a></div>@endcan
@if($module==='paie')<div class="col-12"><fieldset class="border rounded-3 p-3"><legend class="float-none w-auto px-2 fs-6 fw-semibold">Appliquer les retenues, taxes et cotisations ?</legend><div class="form-check form-check-inline"><input class="form-check-input" type="radio" name="appliquer_retenues" id="retenues-oui" value="1" checked><label class="form-check-label" for="retenues-oui">Oui</label></div><div class="form-check form-check-inline"><input class="form-check-input" type="radio" name="appliquer_retenues" id="retenues-non" value="0"><label class="form-check-label" for="retenues-non">Non</label></div><div class="form-text">Si « Non » est choisi, seules les rubriques de gain seront prises en compte.</div></fieldset></div>@endif
@else<div class="col-md-3"><label class="form-label">Période</label><input name="periode" class="form-control" placeholder="Ex. 2026 - Semestre 1" required></div><div class="col-md-2"><label class="form-label">Note /100</label><input type="number" min="0" max="100" name="note" class="form-control" required></div><div class="col-md-3"><label class="form-label">Objectifs</label><input name="objectifs" class="form-control"></div><div class="col-md-4"><label class="form-label">Commentaire</label><input name="commentaire" class="form-control"></div>@endif
<div class="col-12 text-end"><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Enregistrer</button></div></form></div></div>@endif
@include('ressources_humaines._table_'.$module)
<div class="mt-3">{{ $elements->links() }}</div>
</div>
@if($module==='presences')
@push('scripts')<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('form[action$="/presences"]'),box=document.getElementById('presence-calcul');if(!form||!box)return;const minutes=v=>{if(!v)return null;const [h,m]=v.split(':').map(Number);return h*60+m},show=(key,value,suffix)=>box.querySelector(`[data-resultat="${key}"]`).textContent=value+suffix;function calculer(){const option=form.elements.employe_id.selectedOptions[0],arrivee=minutes(form.elements.heure_arrivee.value),depart=minutes(form.elements.heure_depart.value);if(!option?.dataset.debut||arrivee===null||depart===null){show('travaillees','0,00',' h');show('retard',0,' min');show('depart',0,' min');show('supplementaires','0,00',' h');return}const debut=minutes(option.dataset.debut),fin=minutes(option.dataset.fin),pauseDebut=minutes(form.elements.debut_pause.value),pauseFin=minutes(form.elements.fin_pause.value),pause=pauseDebut!==null&&pauseFin!==null?Math.max(0,pauseFin-pauseDebut):Number(option.dataset.pause||0),travaillees=Math.max(0,depart-arrivee-pause)/60,retard=Math.max(0,arrivee-debut-Number(option.dataset.tolerance||0)),anticipe=Math.max(0,fin-depart),supp=Math.max(0,travaillees-Number(option.dataset.heures||0));show('travaillees',travaillees.toFixed(2).replace('.',','),' h');show('retard',retard,' min');show('depart',anticipe,' min');show('supplementaires',supp.toFixed(2).replace('.',','),' h')}form.addEventListener('input',calculer);form.addEventListener('change',calculer);calculer()});
</script>@endpush
@endif
@endsection
