@extends('layouts.app')
@section('title',ucfirst($module))
@section('module-sidebar') @include('ressources_humaines._sidebar') @endsection
@section('content')
@php($titres=['contrats'=>'Contrats','presences'=>'Présences','conges'=>'Congés','paie'=>'Paie','evaluations'=>'Évaluations'])
<div class="container-fluid py-4"><h2 class="fw-bold">{{ $titres[$module] }}</h2><p class="text-muted">Gestion opérationnelle des {{ strtolower($titres[$module]) }}.</p>@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form method="POST" action="{{ route('parametres.rh.'.$module.'.store') }}" class="row g-3">@csrf
<div class="col-md-4"><label class="form-label">Employé</label><select name="user_id" class="form-select" required><option value="">Sélectionner</option>@foreach($employes as $e)<option value="{{ $e->id }}">{{ $e->nom }} {{ $e->prenom }}</option>@endforeach</select></div>
@if($module==='contrats')<div class="col-md-2"><label class="form-label">Numéro</label><input name="numero" class="form-control" required></div><div class="col-md-2"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['CDI','CDD','Stage','Consultance'] as $v)<option>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Début</label><input type="date" name="date_debut" class="form-control" required></div><div class="col-md-2"><label class="form-label">Fin</label><input type="date" name="date_fin" class="form-control"></div><div class="col-md-3"><label class="form-label">Salaire de base</label><input type="number" min="0" step=".01" name="salaire_base" class="form-control" required></div><div class="col-md-3"><label class="form-label">Statut</label><select name="statut" class="form-select">@foreach(['Actif','Suspendu','Terminé'] as $v)<option>{{ $v }}</option>@endforeach</select></div>
@elseif($module==='presences')<div class="col-md-2"><label class="form-label">Date</label><input type="date" name="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Arrivée</label><input type="time" name="heure_arrivee" class="form-control"></div><div class="col-md-2"><label class="form-label">Départ</label><input type="time" name="heure_depart" class="form-control"></div><div class="col-md-2"><label class="form-label">Statut</label><select name="statut" class="form-select">@foreach(['Présent','Absent','Retard','Mission'] as $v)<option>{{ $v }}</option>@endforeach</select></div>
@elseif($module==='conges')<div class="col-md-3"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['Annuel','Maladie','Maternité','Paternité','Exceptionnel'] as $v)<option>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Début</label><input type="date" name="date_debut" class="form-control" required></div><div class="col-md-2"><label class="form-label">Fin</label><input type="date" name="date_fin" class="form-control" required></div>
@elseif($module==='paie')<div class="col-md-2"><label class="form-label">Année</label><input type="number" name="annee" value="{{ now()->year }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Mois</label><input type="number" min="1" max="12" name="mois" value="{{ now()->month }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Salaire</label><input type="number" min="0" step=".01" name="salaire_base" class="form-control" required></div><div class="col-md-2"><label class="form-label">Primes</label><input type="number" min="0" step=".01" name="primes" value="0" class="form-control"></div><div class="col-md-2"><label class="form-label">Retenues</label><input type="number" min="0" step=".01" name="retenues" value="0" class="form-control"></div><div class="col-md-2"><label class="form-label">Monnaie</label><select name="monnaie" class="form-select"><option>CDF</option><option>USD</option></select></div><div class="col-md-2"><label class="form-label">Statut</label><select name="statut" class="form-select"><option>Brouillon</option><option>Validée</option><option>Payée</option></select></div>
@else<div class="col-md-3"><label class="form-label">Période</label><input name="periode" class="form-control" placeholder="Ex. 2026 - Semestre 1" required></div><div class="col-md-2"><label class="form-label">Note /100</label><input type="number" min="0" max="100" name="note" class="form-control" required></div><div class="col-md-3"><label class="form-label">Objectifs</label><input name="objectifs" class="form-control"></div><div class="col-md-4"><label class="form-label">Commentaire</label><input name="commentaire" class="form-control"></div>@endif
<div class="col-12 text-end"><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Enregistrer</button></div></form></div></div>
@include('ressources_humaines._table_'.$module)
</div>@endsection
