<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::table('departements', function (Blueprint $t) {
            $t->foreignId('entreprise_id')->nullable()->constrained('entreprises')->nullOnDelete();
            $t->string('code', 30)->nullable(); $t->text('description')->nullable();
            $t->foreignId('responsable_employe_id')->nullable(); $t->boolean('actif')->default(true);
            $t->unique(['entreprise_id','code']); $t->index(['entreprise_id','actif']);
        });
        Schema::create('rh_sites', function (Blueprint $t) { $t->id(); $t->foreignId('entreprise_id')->constrained('entreprises')->cascadeOnDelete(); $t->string('code',30); $t->string('nom'); $t->text('adresse')->nullable(); $t->boolean('actif')->default(true); $t->timestamps(); $t->unique(['entreprise_id','code']); });
        Schema::create('rh_services', function (Blueprint $t) { $t->id(); $t->foreignId('entreprise_id')->constrained('entreprises')->cascadeOnDelete(); $t->foreignId('departement_id')->constrained('departements')->restrictOnDelete(); $t->string('code',30); $t->string('nom'); $t->text('description')->nullable(); $t->foreignId('responsable_employe_id')->nullable(); $t->boolean('actif')->default(true); $t->timestamps(); $t->unique(['entreprise_id','code']); });
        Schema::table('fonctions', function (Blueprint $t) { $t->foreignId('entreprise_id')->nullable()->constrained('entreprises')->nullOnDelete(); $t->foreignId('departement_id')->nullable()->constrained('departements')->nullOnDelete(); $t->string('code',30)->nullable(); $t->text('description')->nullable(); $t->unsignedSmallInteger('niveau_hierarchique')->default(1); $t->decimal('salaire_minimal',18,2)->nullable(); $t->decimal('salaire_maximal',18,2)->nullable(); $t->string('devise',3)->default('CDF'); $t->boolean('actif')->default(true); $t->unique(['entreprise_id','code']); });

        Schema::create('rh_employes', function (Blueprint $t) {
            $t->id(); $t->foreignId('entreprise_id')->constrained('entreprises')->restrictOnDelete(); $t->foreignId('user_id')->nullable()->unique()->constrained('users')->nullOnDelete();
            $t->string('matricule',50); $t->string('nom'); $t->string('postnom')->nullable(); $t->string('prenom')->nullable(); $t->string('sexe',20)->nullable(); $t->date('date_naissance')->nullable(); $t->string('lieu_naissance')->nullable(); $t->string('etat_civil',30)->nullable(); $t->string('nationalite')->nullable(); $t->text('adresse')->nullable(); $t->string('telephone',40)->nullable(); $t->string('email')->nullable(); $t->string('photo')->nullable();
            $t->string('type_piece_identite')->nullable(); $t->string('numero_piece_identite')->nullable(); $t->date('expiration_piece_identite')->nullable(); $t->string('numero_fiscal')->nullable(); $t->string('numero_securite_sociale')->nullable(); $t->string('contact_urgence')->nullable(); $t->string('telephone_urgence',40)->nullable();
            $t->date('date_embauche')->nullable(); $t->foreignId('departement_id')->nullable()->constrained('departements')->nullOnDelete(); $t->foreignId('service_id')->nullable()->constrained('rh_services')->nullOnDelete(); $t->foreignId('fonction_id')->nullable()->constrained('fonctions')->nullOnDelete(); $t->foreignId('superieur_id')->nullable()->constrained('rh_employes')->nullOnDelete(); $t->foreignId('site_id')->nullable()->constrained('rh_sites')->nullOnDelete();
            $t->string('statut',30)->default('Brouillon'); $t->date('date_depart')->nullable(); $t->text('motif_depart')->nullable(); $t->text('compte_bancaire')->nullable(); $t->string('mode_paiement',30)->nullable(); $t->timestamps(); $t->softDeletes();
            $t->unique(['entreprise_id','matricule']); $t->index(['entreprise_id','statut']); $t->index(['nom','prenom']); $t->index(['departement_id','fonction_id']);
        });
        Schema::table('departements', fn(Blueprint $t)=>$t->foreign('responsable_employe_id')->references('id')->on('rh_employes')->nullOnDelete());
        Schema::table('rh_services', fn(Blueprint $t)=>$t->foreign('responsable_employe_id')->references('id')->on('rh_employes')->nullOnDelete());

        foreach (['rh_contrats','rh_presences','rh_conges','rh_paies','rh_evaluations'] as $table) Schema::table($table, function(Blueprint $t){ $t->unsignedBigInteger('user_id')->nullable()->change(); $t->foreignId('entreprise_id')->nullable()->constrained('entreprises')->nullOnDelete(); $t->foreignId('employe_id')->nullable()->constrained('rh_employes')->nullOnDelete(); $t->softDeletes(); });
        Schema::table('rh_contrats', function(Blueprint $t){ $t->foreignId('fonction_id')->nullable()->constrained('fonctions')->nullOnDelete(); $t->foreignId('departement_id')->nullable()->constrained('departements')->nullOnDelete(); $t->unsignedSmallInteger('periode_essai_jours')->default(0); $t->decimal('heures_hebdomadaires',5,2)->default(40); $t->string('devise',3)->default('CDF'); $t->string('lieu_travail')->nullable(); $t->string('document_signe')->nullable(); $t->foreignId('cree_par')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('valide_par')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('valide_le')->nullable(); $t->text('motif_resiliation')->nullable(); $t->date('date_resiliation')->nullable(); });
        Schema::table('rh_presences', function(Blueprint $t){ $t->time('debut_pause')->nullable(); $t->time('fin_pause')->nullable(); $t->decimal('heures_travaillees',6,2)->default(0); $t->unsignedSmallInteger('retard_minutes')->default(0); $t->unsignedSmallInteger('depart_anticipe_minutes')->default(0); $t->decimal('heures_supplementaires',6,2)->default(0); $t->string('justificatif')->nullable(); $t->string('statut_validation',30)->default('Brouillon'); $t->foreignId('valide_par')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('valide_le')->nullable(); });
        Schema::table('rh_presences', fn(Blueprint $t)=>$t->unique(['employe_id','date'],'rh_presence_employe_date_unique'));
        Schema::table('rh_paies', function(Blueprint $t){ $t->decimal('total_gains',18,2)->default(0); $t->decimal('salaire_brut',18,2)->default(0); $t->decimal('salaire_imposable',18,2)->default(0); $t->decimal('total_taxes',18,2)->default(0); $t->decimal('total_cotisations',18,2)->default(0); $t->decimal('salaire_net',18,2)->default(0); $t->foreignId('cree_par')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('valide_par')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('paye_par')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('valide_le')->nullable(); $t->string('mode_paiement',30)->nullable(); $t->string('reference_paiement')->nullable(); $t->text('commentaire')->nullable(); $t->text('motif_annulation')->nullable(); });
        Schema::table('rh_paies', fn(Blueprint $t)=>$t->unique(['employe_id','annee','mois'],'rh_paie_employe_periode_unique'));

        Schema::create('rh_types_conges', function(Blueprint $t){ $t->id(); $t->foreignId('entreprise_id')->constrained('entreprises')->cascadeOnDelete(); $t->string('code',30); $t->string('libelle'); $t->decimal('jours_annuels',6,2)->default(0); $t->boolean('paye')->default(true); $t->boolean('justificatif_obligatoire')->default(false); $t->boolean('report_autorise')->default(false); $t->decimal('plafond_report',6,2)->default(0); $t->unsignedSmallInteger('max_jours_consecutifs')->nullable(); $t->string('sexe')->nullable(); $t->unsignedSmallInteger('anciennete_min_mois')->default(0); $t->boolean('actif')->default(true); $t->timestamps(); $t->unique(['entreprise_id','code']); });
        Schema::create('rh_soldes_conges', function(Blueprint $t){ $t->id(); $t->foreignId('employe_id')->constrained('rh_employes')->cascadeOnDelete(); $t->foreignId('type_conge_id')->constrained('rh_types_conges')->restrictOnDelete(); $t->year('annee'); $t->decimal('jours_acquis',6,2)->default(0); $t->decimal('jours_reportes',6,2)->default(0); $t->decimal('ajustements',6,2)->default(0); $t->decimal('jours_consommes',6,2)->default(0); $t->timestamps(); $t->unique(['employe_id','type_conge_id','annee']); });
        Schema::table('rh_conges', function(Blueprint $t){ $t->foreignId('type_conge_id')->nullable()->constrained('rh_types_conges')->nullOnDelete(); $t->foreignId('remplacant_id')->nullable()->constrained('rh_employes')->nullOnDelete(); $t->decimal('nombre_jours',6,2)->default(0); $t->string('justificatif')->nullable(); $t->text('motif_rejet')->nullable(); $t->foreignId('responsable_valide_par')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('responsable_valide_le')->nullable(); });
        Schema::create('rh_documents', function(Blueprint $t){ $t->id(); $t->foreignId('entreprise_id')->constrained('entreprises')->cascadeOnDelete(); $t->foreignId('employe_id')->nullable()->constrained('rh_employes')->nullOnDelete(); $t->nullableMorphs('documentable'); $t->string('type',50); $t->string('nom_original'); $t->string('chemin'); $t->string('mime_type',100); $t->unsignedBigInteger('taille'); $t->date('date_expiration')->nullable(); $t->foreignId('televerse_par')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); $t->index(['entreprise_id','type']); });
        Schema::create('rh_permissions', function(Blueprint $t){ $t->id(); $t->string('code')->unique(); $t->string('libelle'); $t->timestamps(); });
        Schema::create('rh_permission_role', function(Blueprint $t){ $t->foreignId('role_id')->constrained('roles')->cascadeOnDelete(); $t->foreignId('permission_id')->constrained('rh_permissions')->cascadeOnDelete(); $t->primary(['role_id','permission_id']); });
        Schema::table('audit_logs', function(Blueprint $t){ $t->foreignId('entreprise_id')->nullable()->constrained('entreprises')->nullOnDelete(); $t->string('module',50)->nullable()->index(); });

        $permissions=['viewHRDashboard','viewEmployees','createEmployees','updateEmployees','archiveEmployees','viewEmployeeSensitiveData','manageDepartments','managePositions','viewContracts','manageContracts','validateContracts','viewAttendance','manageAttendance','validateAttendance','requestLeave','viewTeamLeaves','approveManagerLeave','approveHRLeave','manageLeaveBalances','viewPayroll','createPayroll','validatePayroll','payPayroll','cancelPayroll','viewPayslips','manageEvaluations','manageTrainings','manageDisciplinaryActions','viewHRReports','exportHRReports','viewHRAuditLog','manageHRSettings'];
        foreach($permissions as $code) DB::table('rh_permissions')->insert(['code'=>$code,'libelle'=>preg_replace('/(?<!^)[A-Z]/',' $0',$code),'created_at'=>now(),'updated_at'=>now()]);
        $management=['viewHRDashboard','viewEmployees','createEmployees','updateEmployees','archiveEmployees','manageDepartments','managePositions','viewContracts','manageContracts','validateContracts','viewAttendance','manageAttendance','validateAttendance','viewTeamLeaves','approveManagerLeave','approveHRLeave','manageLeaveBalances','manageEvaluations','manageTrainings','viewHRReports','exportHRReports','manageHRSettings'];
        $profiles=['Admin'=>$management,'Directeur Général'=>$management,'Gérant'=>$management,'Gerant'=>$management,'DAF'=>['viewHRDashboard','viewEmployees','viewPayroll','createPayroll','viewPayslips','viewHRReports','exportHRReports'],'Responsable RH'=>array_diff($permissions,['validatePayroll','payPayroll']),'Agent RH'=>['viewHRDashboard','viewEmployees','createEmployees','updateEmployees','viewContracts','manageContracts','viewAttendance','manageAttendance','viewTeamLeaves','approveHRLeave','manageLeaveBalances','manageEvaluations','manageTrainings','viewHRReports','exportHRReports'],'Responsable paie'=>['viewHRDashboard','viewEmployees','viewEmployeeSensitiveData','viewPayroll','createPayroll','viewPayslips','viewHRReports','exportHRReports'],'Validateur paie'=>['viewPayroll','validatePayroll','viewPayslips'],'Auditeur'=>['viewHRDashboard','viewEmployees','viewContracts','viewAttendance','viewTeamLeaves','viewPayroll','viewPayslips','viewHRReports','exportHRReports','viewHRAuditLog'],'Lecture seule'=>['viewHRDashboard','viewEmployees','viewContracts','viewAttendance','viewHRReports']];
        $nouveauxProfils=['Responsable RH','Agent RH','Responsable paie','Validateur paie','Auditeur','Lecture seule'];
        foreach($profiles as $roleName=>$codes){ $role=DB::table('roles')->where('designation',$roleName)->value('id'); if(!$role && in_array($roleName,$nouveauxProfils,true)) $role=DB::table('roles')->insertGetId(['designation'=>$roleName,'observation'=>'Profil RH','created_at'=>now(),'updated_at'=>now()]); if(!$role) continue; foreach($codes as $code) DB::table('rh_permission_role')->insertOrIgnore(['role_id'=>$role,'permission_id'=>DB::table('rh_permissions')->where('code',$code)->value('id')]); }

        $entrepriseId=DB::table('entreprises')->value('id');
        if($entrepriseId) DB::table('users')->where('statut','Actif')->orderBy('id')->get()->each(function($u) use($entrepriseId){ $eid=DB::table('rh_employes')->insertGetId(['entreprise_id'=>$entrepriseId,'user_id'=>$u->id,'matricule'=>'EMP-'.str_pad((string)$u->id,6,'0',STR_PAD_LEFT),'nom'=>$u->nom,'prenom'=>$u->prenom,'adresse'=>$u->adresse,'telephone'=>$u->telephone,'email'=>$u->email,'photo'=>$u->photo,'departement_id'=>$u->departement_id,'fonction_id'=>$u->fonction_id,'statut'=>'Actif','created_at'=>$u->created_at??now(),'updated_at'=>$u->updated_at??now()]); foreach(['rh_contrats','rh_presences','rh_conges','rh_paies','rh_evaluations'] as $table) DB::table($table)->where('user_id',$u->id)->update(['entreprise_id'=>$entrepriseId,'employe_id'=>$eid]); });
    }
    public function down(): void { throw new RuntimeException('Migration RH progressive non réversible automatiquement afin de protéger les données.'); }
};
