<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Schema};
return new class extends Migration {public function up():void{
 Schema::table('rh_employes',function(Blueprint $t){$t->string('banque')->nullable();$t->string('numero_compte')->nullable();$t->string('operateur_mobile_money')->nullable();$t->string('numero_mobile_money',50)->nullable();});
 Schema::table('rh_contrats',function(Blueprint $t){$t->foreignId('service_id')->nullable()->constrained('rh_services')->nullOnDelete();$t->string('intitule_autre')->nullable();$t->text('description')->nullable();$t->decimal('prime_fonction',18,2)->default(0);$t->decimal('prime_transport',18,2)->default(0);$t->decimal('prime_logement',18,2)->default(0);$t->json('avantages')->nullable();$t->text('conditions_particulieres')->nullable();$t->boolean('regle_presence')->default(true);$t->boolean('regle_conge')->default(true);$t->boolean('regle_retenue_absence')->default(true);$t->boolean('regle_heures_supplementaires')->default(true);});
 Schema::create('rh_periodes_paie',function(Blueprint $t){$t->id();$t->foreignId('entreprise_id')->constrained('entreprises')->cascadeOnDelete();$t->string('libelle');$t->date('date_debut');$t->date('date_fin');$t->unsignedSmallInteger('annee');$t->unsignedTinyInteger('mois');$t->string('statut',30)->default('Ouverte');$t->foreignId('cree_par')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('validee_par')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('validee_le')->nullable();$t->timestamps();$t->unique(['entreprise_id','annee','mois']);});
 Schema::table('rh_syntheses_mensuelles',fn(Blueprint $t)=>$t->foreignId('periode_paie_id')->nullable()->constrained('rh_periodes_paie')->nullOnDelete());Schema::table('rh_paies',fn(Blueprint $t)=>$t->foreignId('periode_paie_id')->nullable()->constrained('rh_periodes_paie')->nullOnDelete());
 $codes=['manageAmendments','correctAttendance','validateAttendance','manageAbsences','validateAbsences','generateMonthlySummary','validateMonthlySummary','preparePayroll','editDraftPayroll','verifyPayroll','validatePayroll','payPayroll','downloadPayslips'];foreach($codes as $c)DB::table('rh_permissions')->insertOrIgnore(['code'=>$c,'libelle'=>preg_replace('/(?<!^)[A-Z]/',' $0',$c),'created_at'=>now(),'updated_at'=>now()]);
 }public function down():void{Schema::table('rh_paies',fn(Blueprint $t)=>$t->dropConstrainedForeignId('periode_paie_id'));Schema::table('rh_syntheses_mensuelles',fn(Blueprint $t)=>$t->dropConstrainedForeignId('periode_paie_id'));Schema::dropIfExists('rh_periodes_paie');}}
;
