<?php
namespace App\Http\Controllers;
use App\Http\Requests\{StoreEmployeRequest,UpdateEmployeRequest};
use App\Models\{Departement,Employe,Fonction,RhService,RhSite,User};
use App\Services\{AuditLogService,CurrentEntreprise,MatriculeEmployeService};
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class EmployeController extends Controller {
 public function index(Request $r,CurrentEntreprise $ctx){$e=$ctx->for();$q=Employe::with(['departement','fonction','service'])->where('entreprise_id',$e->id)->search($r->string('q'))->when($r->filled('departement_id'),fn($q)=>$q->where('departement_id',$r->integer('departement_id')))->when($r->filled('fonction_id'),fn($q)=>$q->where('fonction_id',$r->integer('fonction_id')))->when($r->filled('sexe'),fn($q)=>$q->where('sexe',$r->sexe))->when($r->filled('statut'),fn($q)=>$q->where('statut',$r->statut))->orderBy('nom');return view('ressources_humaines.employes.index',['employes'=>$q->paginate(20)->withQueryString(),'departements'=>Departement::orderBy('designation')->get(),'fonctions'=>Fonction::orderBy('designation')->get()]);}
 public function create(CurrentEntreprise $ctx){return view('ressources_humaines.employes.form',$this->refs($ctx->for()->id)+['employe'=>new Employe]);}
 public function store(StoreEmployeRequest $r,CurrentEntreprise $ctx,MatriculeEmployeService $mat){$ent=$ctx->for();$m=DB::transaction(function()use($r,$ent,$mat){$d=$r->validated();$d['entreprise_id']=$ent->id;$d['matricule']=$d['matricule']?:$mat->generer($ent->id);return Employe::create($d);});app(AuditLogService::class)->record('creation_rh',$m,$m->matricule,null,null,$m->toArray(),[],$r);return redirect()->route('parametres.rh.employes.show',$m)->with('success','Employé créé.');}
 public function show(Employe $employe,CurrentEntreprise $ctx){abort_unless($employe->entreprise_id===$ctx->for()->id,404);$employe->load(['departement','fonction','service','site','superieur','contrats','conges','evaluations']);return view('ressources_humaines.employes.show',compact('employe'));}
 public function edit(Employe $employe,CurrentEntreprise $ctx){abort_unless($employe->entreprise_id===$ctx->for()->id,404);return view('ressources_humaines.employes.form',$this->refs($employe->entreprise_id)+compact('employe'));}
 public function update(UpdateEmployeRequest $r,Employe $employe,CurrentEntreprise $ctx){abort_unless($employe->entreprise_id===$ctx->for()->id,404);$old=$employe->toArray();DB::transaction(fn()=>$employe->update($r->validated()));app(AuditLogService::class)->record('modification_rh',$employe,$employe->matricule,null,$old,$employe->fresh()->toArray(),[],$r);return back()->with('success','Fiche mise à jour.');}
 public function destroy(Request $r,Employe $employe,CurrentEntreprise $ctx){abort_unless($employe->entreprise_id===$ctx->for()->id,404);$old=$employe->toArray();DB::transaction(fn()=>$employe->update(['statut'=>'Archivé'])&&$employe->delete());app(AuditLogService::class)->record('archivage_rh',$employe,$employe->matricule,$r->motif,$old,$employe->toArray(),[],$r,'soft_delete');return redirect()->route('parametres.rh.employes')->with('success','Employé archivé.');}
 public function pdf(Employe $employe,CurrentEntreprise $ctx){abort_unless($employe->entreprise_id===$ctx->for()->id,404);return Pdf::loadView('ressources_humaines.employes.pdf',compact('employe'))->download('fiche-'.$employe->matricule.'.pdf');}
 private function refs(int $eid):array{return ['departements'=>Departement::where(fn($q)=>$q->where('entreprise_id',$eid)->orWhereNull('entreprise_id'))->where('actif',true)->orderBy('designation')->get(),'fonctions'=>Fonction::where(fn($q)=>$q->where('entreprise_id',$eid)->orWhereNull('entreprise_id'))->where('actif',true)->orderBy('designation')->get(),'services'=>RhService::where('entreprise_id',$eid)->where('actif',true)->get(),'sites'=>RhSite::where('entreprise_id',$eid)->where('actif',true)->get(),'superieurs'=>Employe::where('entreprise_id',$eid)->where('statut','Actif')->orderBy('nom')->get(),'utilisateurs'=>User::doesntHave('employe')->orderBy('nom')->get()];}
}
