<?php

namespace App\Http\Controllers;

use App\Models\{Departement,Employe,Fonction,RhConge,RhContrat,RhEvaluation,RhPaie,RhPresence,RhRubriquePaie,User};
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Services\AuditLogService;
use Illuminate\Validation\ValidationException;
use App\Services\CurrentEntreprise;
use App\Services\RhPaymentReferenceService;

class RessourceHumaineController extends Controller
{
    public function index() { return view('ressources_humaines.index', ['nombreEmployes'=>User::count(),'employesActifs'=>User::where('statut','Actif')->count(),'nombreDepartements'=>Departement::count(),'nombreFonctions'=>Fonction::count(),'congesAttente'=>RhConge::where('statut','En attente')->count(),'contratsExpiration'=>RhContrat::where('statut','Actif')->whereBetween('date_fin',[now(),now()->addDays(30)])->count()]); }
    public function employes() { return view('ressources_humaines.employes',['employes'=>User::with(['departement','fonction'])->orderBy('nom')->paginate(20)]); }
    public function contrats() { return $this->page('contrats',RhContrat::with('employe')->latest('date_debut')->paginate(20)); }
    public function presences() { return $this->page('presences',RhPresence::with('employe')->latest('date')->paginate(20)); }
    public function conges() { return $this->page('conges',RhConge::with(['employe','validateur'])->latest()->paginate(20)); }
    public function paie() { return $this->page('paie',RhPaie::with('employe')->orderByDesc('annee')->orderByDesc('mois')->paginate(20)); }
    public function evaluations() { return $this->page('evaluations',RhEvaluation::with(['employe','evaluateur'])->latest()->paginate(20)); }
    public function rapports() { return view('ressources_humaines.rapports',['effectif'=>User::with(['departement','fonction'])->orderBy('nom')->get(),'paies'=>RhPaie::with('employe')->get(),'conges'=>RhConge::with('employe')->get()]); }

    public function storeContrat(Request $r) { $d=$r->validate(['user_id'=>'required|exists:users,id','numero'=>'required|string|max:50|unique:rh_contrats','type'=>'required|in:CDI,CDD,Stage,Consultance','date_debut'=>'required|date','date_fin'=>'required_if:type,CDD|nullable|date|after_or_equal:date_debut','salaire_base'=>'required|numeric|min:0','statut'=>'required|in:Actif,Suspendu,Terminé','observations'=>'nullable|string']); if($d['statut']==='Actif' && RhContrat::where('user_id',$d['user_id'])->where('statut','Actif')->whereDate('date_debut','<=',$d['date_fin']??'9999-12-31')->where(fn($q)=>$q->whereNull('date_fin')->orWhereDate('date_fin','>=',$d['date_debut']))->exists()) throw ValidationException::withMessages(['date_debut'=>'Un contrat actif chevauche déjà cette période.']); $m=RhContrat::create($d); $this->audit($r,'creation_rh',$m,null,$m->toArray()); return back()->with('success','Contrat enregistré.'); }
    public function storePresence(Request $r) { $d=$r->validate(['user_id'=>'required|exists:users,id','date'=>'required|date','heure_arrivee'=>'nullable|date_format:H:i','heure_depart'=>'nullable|date_format:H:i|after:heure_arrivee','statut'=>'required|in:Présent,Absent,Retard,Mission','observation'=>'nullable|string']); $m=RhPresence::where(['user_id'=>$d['user_id'],'date'=>$d['date']])->first(); $old=$m?->toArray(); $m ? $m->update($d) : $m=RhPresence::create($d); $this->audit($r,$old?'modification_rh':'creation_rh',$m,$old,$m->fresh()->toArray()); return back()->with('success','Présence enregistrée.'); }
    public function storeConge(Request $r) { $d=$r->validate(['user_id'=>'required|exists:users,id','type'=>'required|in:Annuel,Maladie,Maternité,Paternité,Exceptionnel','date_debut'=>'required|date','date_fin'=>'required|date|after_or_equal:date_debut','motif'=>'nullable|string']); $overlap=RhConge::where('user_id',$d['user_id'])->whereIn('statut',['En attente','Approuvé'])->whereDate('date_debut','<=',$d['date_fin'])->whereDate('date_fin','>=',$d['date_debut'])->exists(); if($overlap) throw ValidationException::withMessages(['date_debut'=>'Un congé en attente ou approuvé chevauche cette période.']); $m=RhConge::create($d); $this->audit($r,'creation_rh',$m,null,$m->toArray()); return back()->with('success','Demande de congé enregistrée.'); }
    public function statutConge(Request $r,RhConge $conge) { $d=$r->validate(['statut'=>'required|in:Approuvé,Rejeté']); if($conge->statut!=='En attente') throw ValidationException::withMessages(['statut'=>'Seule une demande en attente peut être traitée.']); if($conge->user_id===Auth::id()) throw ValidationException::withMessages(['statut'=>'Vous ne pouvez pas traiter votre propre congé.']); $old=$conge->toArray(); $conge->update($d+['valide_par'=>Auth::id(),'valide_le'=>now()]); $this->audit($r,'validation_rh',$conge,$old,$conge->fresh()->toArray()); return back()->with('success','Demande mise à jour.'); }
    public function storePaie(Request $r, RhPaymentReferenceService $references) { $d=$r->validate(['user_id'=>'required|exists:users,id','annee'=>'required|integer|min:2000|max:2100','mois'=>'required|integer|min:1|max:12','salaire_base'=>'required|numeric|min:0','primes'=>'nullable|numeric|min:0','retenues'=>'nullable|numeric|min:0','monnaie'=>'required|in:CDF,USD','statut'=>'required|in:Brouillon,Validée,Payée','date_paiement'=>'required_if:statut,Payée|nullable|date','mode_paiement'=>'required_if:statut,Payée|nullable|in:Cash,Mobile money,Virement bancaire']); $d['primes']=$d['primes']??0; $d['retenues']=$d['retenues']??0; $employe=Employe::where('user_id',$d['user_id'])->firstOrFail(); $d['employe_id']=$employe->id; $d['entreprise_id']=$employe->entreprise_id; if($d['statut']==='Payée'){$d['reference_paiement']=$references->generate($employe->entreprise_id,(int)$d['annee'],(int)$d['mois']);}else{$d['date_paiement']=null;$d['mode_paiement']=null;$d['reference_paiement']=null;} if($d['retenues']>$d['salaire_base']+$d['primes']) throw ValidationException::withMessages(['retenues'=>'Les retenues ne peuvent pas rendre le net négatif.']); $m=RhPaie::where(['employe_id'=>$employe->id,'annee'=>$d['annee'],'mois'=>$d['mois']])->first(); if($m && $m->statut!=='Brouillon') throw ValidationException::withMessages(['mois'=>'Une paie validée ou payée ne peut plus être remplacée.']); $old=$m?->toArray(); $m ? $m->update($d) : $m=RhPaie::create($d); $this->audit($r,$old?'modification_rh':'creation_rh',$m,$old,$m->fresh()->toArray()); return back()->with('success','Paie enregistrée sous la référence '.$m->reference_paiement.'.'); }
    public function storeEvaluation(Request $r) { $m=RhEvaluation::create($r->validate(['user_id'=>'required|exists:users,id','periode'=>'required|string|max:50','note'=>'required|integer|min:0|max:100','objectifs'=>'nullable|string','commentaire'=>'nullable|string'])+['evalue_par'=>Auth::id()]); $this->audit($r,'creation_rh',$m,null,$m->toArray()); return back()->with('success','Évaluation enregistrée.'); }
    public function destroy(Request $r,string $type,int $id) { $model=match($type){'contrats'=>RhContrat::class,'presences'=>RhPresence::class,'conges'=>RhConge::class,'paie'=>RhPaie::class,'evaluations'=>RhEvaluation::class,default=>abort(404)}; $m=$model::findOrFail($id); if($m instanceof RhPaie && $m->statut!=='Brouillon') throw ValidationException::withMessages(['suppression'=>'Une paie validée ou payée ne peut pas être supprimée.']); if($m instanceof RhConge && $m->statut==='Approuvé') throw ValidationException::withMessages(['suppression'=>'Un congé approuvé doit être conservé.']); $old=$m->toArray(); $this->audit($r,'suppression_rh',$m,$old,null); $m->delete(); return back()->with('success','Enregistrement supprimé.'); }
    public function report(string $format) { $data=['titre'=>'Rapport des ressources humaines','headers'=>['Employé','Département','Fonction','Statut'],'rows'=>User::with(['departement','fonction'])->orderBy('nom')->get()->map(fn($u)=>[$u->nom.' '.$u->prenom,$u->departement?->designation??'—',$u->fonction?->designation??'—',$u->statut]),'dateDebut'=>now()->startOfYear()->toDateString(),'dateFin'=>now()->toDateString(),'entreprise'=>\App\Models\Entreprise::first()]; if($format==='print') return view('budgets.report',$data); if($format==='pdf') return Pdf::loadView('exports.table',$data)->setPaper('a4','landscape')->download('rapport-rh.pdf'); $content=view('exports.table_excel',$data)->render(); return response("\xEF\xBB\xBF".$content,200,['Content-Type'=>'application/vnd.ms-excel; charset=UTF-8','Content-Disposition'=>'attachment; filename="rapport-rh.xls"']); }
    public function bulletin(Request $request, RhPaie $paie, CurrentEntreprise $contexte)
    {
        $entreprise = $contexte->for($request->user());
        abort_unless((int) $paie->entreprise_id === (int) $entreprise->id, 404);
        $paie->loadMissing(['employe.departement', 'employe.fonction', 'lignes']);
        abort_unless($paie->employe, 404, 'Cette paie doit être rattachée à une fiche employé.');
        $this->audit($request, 'telechargement_bulletin_rh', $paie, null, ['format' => 'pdf']);
        $identifiant = $paie->reference_paiement ?: $paie->annee.'-'.str_pad((string) $paie->mois, 2, '0', STR_PAD_LEFT);
        $nom = 'bulletin-'.$paie->employe->matricule.'-'.$identifiant.'.pdf';
        return Pdf::loadView('ressources_humaines.paie.bulletin', compact('paie', 'entreprise'))
            ->setPaper('a4')
            ->download($nom);
    }
    private function page(string $module,$elements) { return view('ressources_humaines.gestion',compact('module','elements')+['employes'=>Employe::where('statut','Actif')->orderBy('nom')->get(),'rubriques'=>RhRubriquePaie::where('actif',true)->orderBy('type')->orderBy('code')->get()]); }
    private function audit(Request $request,string $action,$model,?array $old,?array $new): void { app(AuditLogService::class)->record($action,$model,(string)$model->getKey(),null,$old,$new,[],$request); }
}
