<?php
namespace App\Http\Controllers;
use App\Http\Requests\StoreRhContratRequest;use App\Models\{Employe,RhContrat};use App\Services\{AuditLogService,CurrentEntreprise,RhContratService,RhContractNumberService};use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Illuminate\Validation\ValidationException;
class RhContratController extends Controller{
 public function index(Request $r,CurrentEntreprise $ctx){$id=$ctx->for()->id;$q=RhContrat::with(['employe','fonction','service'])->where('entreprise_id',$id)->when($r->filled('type'),fn($q)=>$q->where('type',$r->type))->when($r->filled('statut'),fn($q)=>$q->where('statut',$r->statut))->when($r->filled('q'),fn($q)=>$q->where(fn($q)=>$q->where('numero','like','%'.$r->q.'%')->orWhereHas('employe',fn($e)=>$e->where('matricule','like','%'.$r->q.'%')->orWhere('nom','like','%'.$r->q.'%'))));return view('ressources_humaines.gestion',['module'=>'contrats','elements'=>$q->latest('date_debut')->paginate(20)->withQueryString(),'employes'=>Employe::where('entreprise_id',$id)->where('statut','Actif')->orderBy('nom')->get()]);}
 public function store(StoreRhContratRequest $r,RhContratService $s){$m=$s->creer($r->validated(),$r->user()->id);$this->audit($r,'creation_contrat_rh',$m,null,$m->toArray());return redirect()->route('parametres.rh.contrats.show',$m)->with('success','Contrat '.$m->numero.' enregistré.');}
 public function show(Request $r,RhContrat $contrat,CurrentEntreprise $c){$this->guard($contrat,$c);$contrat->load(['employe','departement','service','fonction','superieur','avenants','renouvellements','paies']);return view('ressources_humaines.contrats.show',compact('contrat'));}
 public function soumettre(Request $r,RhContrat $contrat,RhContratService $s,CurrentEntreprise $c){$this->guard($contrat,$c);$old=$contrat->toArray();$s->soumettre($contrat,$r->user()->id);$this->audit($r,'soumission_contrat_rh',$contrat,$old,$contrat->fresh()->toArray());return back()->with('success','Contrat soumis à validation.');}
 public function validateContract(Request $r,RhContrat $contrat,RhContratService $s,CurrentEntreprise $c){$this->guard($contrat,$c);$old=$contrat->toArray();$s->valider($contrat,$r->user()->id);$this->audit($r,'validation_contrat_rh',$contrat,$old,$contrat->fresh()->toArray());return back()->with('success','Contrat validé. Il peut maintenant être activé.');}
 public function activer(Request $r,RhContrat $contrat,RhContratService $s,CurrentEntreprise $c){$this->guard($contrat,$c);$old=$contrat->toArray();$s->activer($contrat,$r->user()->id);$this->audit($r,'activation_contrat_rh',$contrat,$old,$contrat->fresh()->toArray());return back()->with('success','Contrat activé.');}
 public function renouveler(Request $r,RhContrat $contrat,RhContratService $s,RhContractNumberService $n,CurrentEntreprise $c){$this->guard($contrat,$c);$d=$r->validate(['date_debut'=>'required|date|after_or_equal:'.$contrat->date_debut->toDateString(),'date_fin'=>'nullable|date|after_or_equal:date_debut']);$copie=$contrat->replicate(['numero','statut','valide_par','valide_le','date_fin_reelle','type_fin','observation_fin']);$copie->fill($d+['numero'=>$n->contrat($contrat->entreprise_id,(int)date('Y',strtotime($d['date_debut']))),'contrat_precedent_id'=>$contrat->id,'statut'=>'Brouillon','cree_par'=>$r->user()->id])->save();$this->audit($r,'renouvellement_contrat_rh',$copie,null,$copie->toArray());return redirect()->route('parametres.rh.contrats.show',$copie)->with('success','Renouvellement créé sans modifier le contrat précédent.');}
 public function terminer(Request $r,RhContrat $contrat,CurrentEntreprise $c){$this->guard($contrat,$c);$d=$r->validate(['date_fin_reelle'=>'required|date|after_or_equal:'.$contrat->date_debut->toDateString(),'type_fin'=>'required|in:Expiration normale,Démission,Licenciement,Rupture de commun accord,Fin de mission,Fin de stage,Non-confirmation après essai,Autre','motif'=>'required|string|min:3','observation_fin'=>'nullable|string']);$old=$contrat->toArray();$contrat->update($d+['date_fin'=>$d['date_fin_reelle'],'statut'=>$d['type_fin']==='Expiration normale'?'Terminé':'Rompu','motif_resiliation'=>$d['motif'],'date_resiliation'=>$d['date_fin_reelle'],'modifie_par'=>$r->user()->id]);$this->audit($r,'fin_contrat_rh',$contrat,$old,$contrat->fresh()->toArray(),$d['motif']);return back()->with('success','Fin du contrat enregistrée.');}
 public function pdf(Request $r,RhContrat $contrat,CurrentEntreprise $c){$this->guard($contrat,$c);$contrat->load(['employe','departement','service','fonction']);$entreprise=$c->for();$this->audit($r,'generation_pdf_contrat_rh',$contrat,null,['format'=>'pdf']);return Pdf::loadView('ressources_humaines.contrats.pdf',compact('contrat','entreprise'))->download('contrat-'.$contrat->numero.'.pdf');}
 private function guard($m,CurrentEntreprise $c):void{abort_unless((int)$m->entreprise_id===(int)$c->for()->id,404);}private function audit(Request $r,string $a,RhContrat $m,?array $old,?array $new,?string $motif=null):void{app(AuditLogService::class)->record($a,$m,$m->numero,$motif,$old,$new,[],$r);}
}
