<?php
namespace App\Http\Controllers;
use App\Models\{Employe,RhPaie,RhRubriquePaie};use App\Services\{AuditLogService,RhPaymentReferenceService};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class RhPaieController extends Controller
{
 public function store(Request $r,RhPaymentReferenceService $refs){
  $d=$r->validate(['user_id'=>'required|exists:users,id','annee'=>'required|integer|min:2000|max:2100','mois'=>'required|integer|min:1|max:12','salaire_base'=>'required|numeric|min:0','monnaie'=>'required|in:CDF,USD','statut'=>'required|in:Brouillon,Validée,Payée','date_paiement'=>'required_if:statut,Payée|nullable|date','mode_paiement'=>'required_if:statut,Payée|nullable|in:Cash,Mobile money,Virement bancaire','appliquer_retenues'=>'required|boolean','rubriques'=>'nullable|array','rubriques.*'=>'nullable|numeric|min:0']);
  $d['appliquer_retenues']=$r->boolean('appliquer_retenues');$e=Employe::where('user_id',$d['user_id'])->firstOrFail();$existant=RhPaie::where(['employe_id'=>$e->id,'annee'=>$d['annee'],'mois'=>$d['mois']])->first();if($existant&&$existant->statut!=='Brouillon')throw ValidationException::withMessages(['mois'=>'Une paie validée ou payée ne peut plus être remplacée.']);
  $rubriques=RhRubriquePaie::where('entreprise_id',$e->entreprise_id)->where('actif',true)->whereIn('id',array_keys($d['rubriques']??[]))->get();$sommes=['Gain'=>0,'Retenue'=>0,'Taxe'=>0,'Cotisation'=>0];$lignes=[];
  foreach($rubriques as $rubrique){if(!$d['appliquer_retenues']&&$rubrique->type!=='Gain')continue;$montant=$rubrique->calculer((float)$d['salaire_base'],isset($d['rubriques'][$rubrique->id])?(float)$d['rubriques'][$rubrique->id]:null);if($montant<=0)continue;$sommes[$rubrique->type]+=$montant;$lignes[]=['rubrique_id'=>$rubrique->id,'code'=>$rubrique->code,'libelle'=>$rubrique->libelle,'type'=>$rubrique->type,'base'=>$d['salaire_base'],'taux'=>$rubrique->mode_calcul==='Taux'?$rubrique->valeur:null,'montant'=>$montant];}
  $d+=['employe_id'=>$e->id,'entreprise_id'=>$e->entreprise_id,'primes'=>$sommes['Gain'],'retenues'=>$sommes['Retenue'],'total_taxes'=>$sommes['Taxe'],'total_cotisations'=>$sommes['Cotisation'],'cree_par'=>$r->user()->id];unset($d['rubriques']);if($d['statut']==='Payée')$d['reference_paiement']=$refs->generate($e->entreprise_id,(int)$d['annee'],(int)$d['mois']);else{$d['date_paiement']=null;$d['mode_paiement']=null;$d['reference_paiement']=null;}if($sommes['Retenue']+$sommes['Taxe']+$sommes['Cotisation']>(float)$d['salaire_base']+$sommes['Gain'])throw ValidationException::withMessages(['rubriques'=>'Le total des retenues dépasse les gains.']);
  $old=$existant?->toArray();$paie=DB::transaction(function()use($existant,$d,$lignes){$existant?$existant->update($d):$existant=RhPaie::create($d);$existant->lignes()->delete();$existant->lignes()->createMany($lignes);return $existant;});app(AuditLogService::class)->record($old?'modification_rh':'creation_rh',$paie,(string)$paie->id,null,$old,$paie->fresh()->toArray(),[],$r);return back()->with('success','Paie enregistrée'.($paie->reference_paiement?' sous la référence '.$paie->reference_paiement:'').'.');
 }
}
