<?php
namespace App\Http\Controllers;
use App\Http\Requests\StoreRhPresenceRequest;
use App\Models\{Departement,Employe,RhHoraire,RhPresence,RhSite};
use App\Services\{CurrentEntreprise,RhPresenceCalculationService,RhWorkflowService};
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class RhPresenceController extends Controller {
    public function index(Request $request,CurrentEntreprise $ctx){$id=$ctx->for()->id;$query=RhPresence::with(['employe.departement','employe.service','employe.site'])->where('entreprise_id',$id)->when($request->filled('date'),fn($q)=>$q->whereDate('date',$request->date))->when($request->filled('date_debut'),fn($q)=>$q->whereDate('date','>=',$request->date_debut))->when($request->filled('date_fin'),fn($q)=>$q->whereDate('date','<=',$request->date_fin))->when($request->filled('employe_id'),fn($q)=>$q->where('employe_id',$request->integer('employe_id')))->when($request->filled('statut'),fn($q)=>$q->where('statut',$request->statut))->when($request->filled('methode_pointage'),fn($q)=>$q->where('methode_pointage',$request->methode_pointage))->when($request->filled('departement_id'),fn($q)=>$q->whereHas('employe',fn($e)=>$e->where('departement_id',$request->integer('departement_id'))))->when($request->filled('site_id'),fn($q)=>$q->whereHas('employe',fn($e)=>$e->where('site_id',$request->integer('site_id'))));$elements=(clone $query)->latest('date')->latest('heure_arrivee')->paginate(20)->withQueryString();$stats=(clone $query)->get();$employes=Employe::with('horaire')->where('entreprise_id',$id)->where('statut','Actif')->orderBy('nom')->get();$statsPresence=['presences'=>$stats->whereIn('statut',['Présent','Retard','Télétravail'])->count(),'absences'=>$stats->whereIn('statut',['Absent','Absence non justifiée'])->count(),'retards'=>$stats->where('retard_minutes','>',0)->count(),'heures_supplementaires'=>$stats->sum('heures_supplementaires')];$horaireDefaut=RhHoraire::where('entreprise_id',$id)->where('par_defaut',true)->first();$departements=Departement::where(fn($q)=>$q->where('entreprise_id',$id)->orWhereNull('entreprise_id'))->orderBy('designation')->get();$sites=RhSite::where('entreprise_id',$id)->orderBy('nom')->get();return view('ressources_humaines.presences.index',compact('elements','employes','statsPresence','horaireDefaut','departements','sites'));}
    public function store(StoreRhPresenceRequest $r,RhPresenceCalculationService $calcul,RhWorkflowService $workflow){$d=$r->validated();$e=Employe::findOrFail($d['employe_id']);$this->sameCompany($r,$e);$valeurs=$calcul->calculate($e,$d);$h=$e->horaire?:RhHoraire::where('entreprise_id',$e->entreprise_id)->where('par_defaut',true)->first();$m=RhPresence::where(['employe_id'=>$e->id,'date'=>$d['date']])->first();if($m&&$m->statut_validation==='Validé')throw ValidationException::withMessages(['date'=>'Un pointage validé doit passer par une correction motivée.']);$avant=$m?->toArray();$data=$d+$valeurs+['entreprise_id'=>$e->entreprise_id,'user_id'=>$e->user_id,'statut_validation'=>'Brouillon','heure_debut_prevue'=>$h?->heure_debut,'heure_fin_prevue'=>$h?->heure_fin];$m?$m->update($data):$m=RhPresence::create($data);$workflow->trace($m,$avant?'modification_pointage':'creation_pointage',$r->user()->id,null,$avant,$m->fresh()->toArray());return back()->with('success','Pointage enregistré en brouillon.');}
    public function transition(Request $r,RhPresence $presence,RhWorkflowService $workflow){$this->sameCompany($r,$presence);$d=$r->validate(['statut'=>'required|in:À vérifier,Validé,Rejeté','motif'=>'nullable|required_if:statut,Rejeté|string','approuver_heures_supplementaires'=>'nullable|boolean']);$transitions=['Brouillon'=>['À vérifier'],'À vérifier'=>['Validé','Rejeté'],'Rejeté'=>['Brouillon']];$changes=[];if($d['statut']==='Validé')$changes=['valide_par'=>$r->user()->id,'valide_le'=>now(),'heures_supplementaires_approuvees'=>$r->boolean('approuver_heures_supplementaires'),'heures_supplementaires_validees'=>$r->boolean('approuver_heures_supplementaires')?$presence->heures_supplementaires:0];$workflow->transition($presence,$d['statut'],$transitions,$r->user()->id,$d['motif']??null,$changes);return back()->with('success','Statut du pointage mis à jour.');}
    public function corriger(Request $r,RhPresence $presence,RhPresenceCalculationService $calcul,RhWorkflowService $workflow){$this->sameCompany($r,$presence);if($presence->statut_validation!=='Validé')throw ValidationException::withMessages(['statut'=>'Seul un pointage validé utilise cette procédure de correction.']);$d=$r->validate(['heure_arrivee'=>'nullable|date_format:H:i','heure_depart'=>'nullable|date_format:H:i|after:heure_arrivee','debut_pause'=>'nullable|date_format:H:i','fin_pause'=>'nullable|date_format:H:i','statut'=>'required|string','observation'=>'nullable|string','motif_correction'=>'required|string|min:3']);$avant=$presence->toArray();$presence->update($d+$calcul->calculate($presence->employe,$d+['date'=>$presence->date->toDateString()])+['valeurs_avant_correction'=>$avant,'statut_validation'=>'À vérifier','valide_par'=>null,'valide_le'=>null,'heures_supplementaires_approuvees'=>false,'heures_supplementaires_validees'=>0]);$workflow->trace($presence,'correction_pointage',$r->user()->id,$d['motif_correction'],$avant,$presence->fresh()->toArray());return back()->with('success','Correction enregistrée et renvoyée à la vérification.');}
    public function exportExcel(){abort(501,'Export en cours de migration.');}
    private function sameCompany(Request $r,$m):void{$eid=app(CurrentEntreprise::class)->for($r->user())->id;abort_unless((int)$m->entreprise_id===(int)$eid,404);}
}
