<?php
namespace App\Http\Controllers;
use App\Models\{RhHoraire,RhRubriquePaie,RhService,RhSite,RhTypeContrat};use App\Services\CurrentEntreprise;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class RhSettingController extends Controller
{
 public function index(CurrentEntreprise $c){$id=$c->for()->id;return view('ressources_humaines.parametres',['rubriques'=>RhRubriquePaie::where('entreprise_id',$id)->orderBy('type')->orderBy('code')->paginate(20,['*'],'rubriques_page'),'horaires'=>RhHoraire::where('entreprise_id',$id)->orderByDesc('par_defaut')->get(),'typesContrats'=>RhTypeContrat::where('entreprise_id',$id)->orderBy('libelle')->get(),'typesConges'=>DB::table('rh_types_conges')->where('entreprise_id',$id)->orderBy('libelle')->get(),'sites'=>RhSite::where('entreprise_id',$id)->orderBy('nom')->get(),'services'=>RhService::where('entreprise_id',$id)->with('departement')->orderBy('nom')->get()]);}
 public function storeSchedule(Request $r,CurrentEntreprise $c){$d=$r->validate(['libelle'=>'required|string|max:120','heure_debut'=>'required|date_format:H:i','heure_debut_pause'=>'nullable|required_with:heure_fin_pause|date_format:H:i|after:heure_debut','heure_fin_pause'=>'nullable|required_with:heure_debut_pause|date_format:H:i|after:heure_debut_pause|before:heure_fin','heure_fin'=>'required|date_format:H:i|after:heure_debut','heures_normales'=>'required|numeric|min:1|max:24','tolerance_retard_minutes'=>'required|integer|min:0|max:180','par_defaut'=>'nullable|boolean']);$d['pause_minutes']=$this->pauseMinutes($d);$id=$c->for()->id;$d['par_defaut']=$r->boolean('par_defaut');DB::transaction(function()use($id,$d){if($d['par_defaut'])RhHoraire::where('entreprise_id',$id)->update(['par_defaut'=>false]);$base='HORAIRE-'.str_pad((string)(RhHoraire::where('entreprise_id',$id)->count()+1),3,'0',STR_PAD_LEFT);$code=$base;$i=1;while(RhHoraire::where('entreprise_id',$id)->where('code',$code)->exists())$code=$base.'-'.$i++;RhHoraire::create($d+['entreprise_id'=>$id,'code'=>$code,'actif'=>true]);});return back()->with('success','Horaire créé.');}
 public function updateSchedule(Request $r,RhHoraire $horaire,CurrentEntreprise $c){abort_unless($horaire->entreprise_id===$c->for()->id,404);$d=$r->validate(['libelle'=>'required|string|max:120','heure_debut'=>'required|date_format:H:i','heure_debut_pause'=>'nullable|required_with:heure_fin_pause|date_format:H:i|after:heure_debut','heure_fin_pause'=>'nullable|required_with:heure_debut_pause|date_format:H:i|after:heure_debut_pause|before:heure_fin','heure_fin'=>'required|date_format:H:i|after:heure_debut','heures_normales'=>'required|numeric|min:1|max:24','tolerance_retard_minutes'=>'required|integer|min:0|max:180','par_defaut'=>'nullable|boolean','actif'=>'nullable|boolean']);$d['pause_minutes']=$this->pauseMinutes($d);$d['par_defaut']=$r->boolean('par_defaut');$d['actif']=$r->boolean('actif');DB::transaction(function()use($horaire,$d){if($d['par_defaut'])RhHoraire::where('entreprise_id',$horaire->entreprise_id)->whereKeyNot($horaire->id)->update(['par_defaut'=>false]);$horaire->update($d);});return back()->with('success','Horaire mis à jour.');}
 public function destroySchedule(RhHoraire $horaire,CurrentEntreprise $c){abort_unless($horaire->entreprise_id===$c->for()->id,404);if($horaire->par_defaut)return back()->with('error','Définissez d’abord un autre horaire principal.');if($horaire->hasMany(\App\Models\Employe::class,'horaire_id')->exists())return back()->with('error','Cet horaire est affecté à un ou plusieurs employés.');$horaire->delete();return back()->with('success','Horaire supprimé.');}
 private function pauseMinutes(array $d):int{if(empty($d['heure_debut_pause'])||empty($d['heure_fin_pause']))return 0;return (int)\Carbon\Carbon::parse($d['heure_debut_pause'])->diffInMinutes(\Carbon\Carbon::parse($d['heure_fin_pause']));}
}
