<?php
namespace App\Http\Controllers;
use App\Models\{Employe,RhSyntheseMensuelle};
use App\Services\{AuditLogService,CurrentEntreprise,RhSyntheseMensuelleService,RhWorkflowService};
use Illuminate\Http\Request;

class RhSyntheseMensuelleController extends Controller {
    public function index(CurrentEntreprise $ctx){$id=$ctx->for()->id;return view('ressources_humaines.syntheses.index',['syntheses'=>RhSyntheseMensuelle::with('employe')->where('entreprise_id',$id)->orderByDesc('annee')->orderByDesc('mois')->paginate(20),'employes'=>Employe::where('entreprise_id',$id)->where('statut','Actif')->orderBy('nom')->get()]);}
    public function store(Request $r,RhSyntheseMensuelleService $service,RhWorkflowService $workflow){$d=$r->validate(['employe_id'=>'required|exists:rh_employes,id','annee'=>'required|integer|min:2000|max:2100','mois'=>'required|integer|min:1|max:12']);$e=Employe::findOrFail($d['employe_id']);$this->sameCompany($r,$e);$s=$service->generer($e,$d['annee'],$d['mois'],$r->user()->id);$workflow->trace($s,'generation_synthese',$r->user()->id,null,null,$s->toArray());return back()->with('success','Synthèse générée à partir des pointages enregistrés.');}
    public function storeAll(Request $r,RhSyntheseMensuelleService $service,RhWorkflowService $workflow){$d=$r->validate(['annee'=>'required|integer|min:2000|max:2100','mois'=>'required|integer|min:1|max:12']);$entreprise=app(CurrentEntreprise::class)->for($r->user());$employes=Employe::where('entreprise_id',$entreprise->id)->where('statut','Actif')->orderBy('nom')->get();$generes=0;$ignores=[];foreach($employes as $employe){try{$avant=RhSyntheseMensuelle::where(['employe_id'=>$employe->id,'annee'=>$d['annee'],'mois'=>$d['mois']])->first()?->toArray();$synthese=$service->generer($employe,$d['annee'],$d['mois'],$r->user()->id);$workflow->trace($synthese,$avant?'regeneration_synthese_collective':'generation_synthese_collective',$r->user()->id,null,$avant,$synthese->toArray());$generes++;}catch(\Illuminate\Validation\ValidationException $exception){$ignores[]=$employe->matricule.' — '.collect($exception->errors())->flatten()->first();}}$message=$generes.' synthèse(s) générée(s) pour '.str_pad((string)$d['mois'],2,'0',STR_PAD_LEFT).'/'.$d['annee'].'.';$response=back()->with('success',$message);if($ignores)$response->with('warning',count($ignores).' synthèse(s) conservée(s) ou ignorée(s) : '.implode(' | ',$ignores));return $response;}
    public function transition(Request $r,RhSyntheseMensuelle $synthese,RhWorkflowService $workflow){$this->sameCompany($r,$synthese);$d=$r->validate(['statut'=>'required|in:À vérifier,Validée','motif'=>'nullable|string']);$transitions=['Générée'=>['À vérifier'],'À vérifier'=>['Validée']];$changes=$d['statut']==='Validée'?['validee_par'=>$r->user()->id,'validee_le'=>now()]:[];$workflow->transition($synthese,$d['statut'],$transitions,$r->user()->id,$d['motif']??null,$changes);return back()->with('success','Synthèse mise à jour.');}
    public function update(Request $r,RhSyntheseMensuelle $synthese,RhWorkflowService $workflow){$this->superAdmin($r);$this->sameCompany($r,$synthese);$d=$r->validate(['jours_ouvrables_prevus'=>'required|integer|min:0|max:31','jours_presents'=>'required|integer|min:0|max:31','jours_conges_payes'=>'required|numeric|min:0|max:31','jours_mission'=>'required|numeric|min:0|max:31','jours_absence_non_remuneree'=>'required|numeric|min:0|max:31','nombre_retards'=>'required|integer|min:0|max:31','retard_total_minutes'=>'required|integer|min:0','heures_supplementaires_validees'=>'required|numeric|min:0','motif_modification'=>'required|string|min:5|max:500']);$avant=$synthese->toArray();$valeurs=collect($d)->except('motif_modification')->all()+['statut'=>'À vérifier','validee_par'=>null,'validee_le'=>null,'verrouillee_le'=>null];$synthese->update($valeurs);$workflow->trace($synthese,'modification_synthese',$r->user()->id,$d['motif_modification'],$avant,$synthese->fresh()->toArray());return back()->with('success','Synthèse modifiée et renvoyée à la vérification.');}
    public function destroy(Request $r,RhSyntheseMensuelle $synthese){$this->superAdmin($r);$this->sameCompany($r,$synthese);$d=$r->validate(['motif_suppression'=>'required|string|min:5|max:500']);$avant=$synthese->toArray();app(AuditLogService::class)->record('suppression_synthese_rh',$synthese,(string)$synthese->id,$d['motif_suppression'],$avant,null,[],$r);$synthese->delete();return back()->with('success','Synthèse supprimée.');}
    private function superAdmin(Request $r):void{abort_unless($r->user()?->isSuperAdmin(),403);}
    private function sameCompany(Request $r,$m):void{abort_unless((int)$m->entreprise_id===(int)app(CurrentEntreprise::class)->for($r->user())->id,404);}
}
