@extends('layouts.app')
@section('content')
<div class="container py-4">
    @if($brc->clotureJournaliere)<div class="alert alert-primary d-flex justify-content-between align-items-center"><span><i class="bi bi-diagram-3 me-2"></i>Généré par la clôture <strong>{{ $brc->clotureJournaliere->numero_cloture }}</strong></span><a class="btn btn-sm btn-primary" href="{{ route('parametres.clotures.show',$brc->clotureJournaliere) }}">Voir la clôture</a></div>@endif
    <div class="d-flex justify-content-between align-items-center mb-3"><div><span class="text-uppercase text-muted small fw-bold">Document comptable</span><h3 class="mb-0"><i class="bi bi-file-earmark-check me-2"></i>{{ $brc->reference }}</h3></div><div class="d-flex gap-2">@can('deleteFinancialDocument')<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalSuppressionDocument"><i class="bi bi-trash me-1"></i>Supprimer</button>@endcan<a href="{{ route('brc.index') }}" class="btn btn-secondary">Retour</a></div></div>
    @include('partials.document-navigation')
    @include('partials.financial-delete-modal', ['documentType'=>'BRC','documentReference'=>$brc->reference,'documentStatus'=>$brc->statut,'deleteRoute'=>route('brc.destroy',$brc)])
    <div class="row g-3 mb-4"><div class="col-md-3"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Date</small><div class="fw-bold">{{ $brc->date?->format('d/m/Y') }}</div></div></div></div><div class="col-md-3"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Statut</small><div><span class="badge bg-{{ $brc->statut==='Validé'?'success':'warning' }}">{{ $brc->statut }}</span></div></div></div></div><div class="col-md-3"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Monnaie / sens</small><div class="fw-bold">{{ $brc->monnaie }} — {{ ucfirst($brc->sens) }}</div></div></div></div><div class="col-md-3"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Total</small><div class="fw-bold">{{ number_format($brc->total,2,',',' ') }} {{ $brc->monnaie }}</div></div></div></div></div>
    @if($brc->piece_justificative)<div class="alert alert-info d-flex justify-content-between align-items-center"><span><i class="bi bi-paperclip me-2"></i>Pièce justificative jointe</span><a href="{{ route('brc.piece', $brc) }}" target="_blank" class="btn btn-sm btn-primary"><i class="bi bi-eye me-1"></i>Consulter</a></div>@endif
    <div class="card border-0 shadow-sm"><div class="card-header bg-dark text-white">Lignes du BRC</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Compte</th><th>Libellé</th><th class="text-end">Montant</th></tr></thead><tbody>@foreach($brc->lignes as $ligne)<tr><td>{{ $ligne->compte?->compte }}</td><td>{{ $ligne->libelle }}</td><td class="text-end">{{ number_format($ligne->montant,2,',',' ') }}</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
