<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Bon d’entrée {{ $entree->numero }}</title>
<style>
@page{size:A4 portrait;margin:18mm 14mm}*{box-sizing:border-box}body{margin:0;color:#172033;font-family:DejaVu Sans,Arial,sans-serif;font-size:12px}.actions{max-width:900px;margin:0 auto 18px;display:flex;justify-content:flex-end;gap:8px}.actions a,.actions button{padding:9px 14px;border:0;border-radius:5px;color:#fff;background:#1d4ed8;text-decoration:none;cursor:pointer}.actions a{background:#475569}.sheet{width:210mm;min-height:297mm;margin:auto;padding:18mm 14mm;background:#fff}.pdf-mode .sheet{width:auto;min-height:auto;padding:0}.header{text-align:center;border-bottom:3px solid #176b4d;padding-bottom:10px;margin-bottom:18px}.logo{display:block;max-width:85px;max-height:85px;margin:0 auto 7px}.company{font-size:20px;font-weight:bold;color:#176b4d;text-transform:uppercase}.slogan{font-style:italic;font-weight:bold;margin:3px 0;color:#334155}.contact{color:#64748b}h1{text-align:center;text-transform:uppercase;font-size:21px;margin:18px 0 3px}.number{text-align:center;color:#475569;margin-bottom:18px}.meta,.lines{width:100%;border-collapse:collapse}.meta{margin-bottom:16px}.meta td{width:50%;padding:7px 9px;border:1px solid #d8dee8}.label{color:#64748b;font-size:10px;text-transform:uppercase}.value{display:block;margin-top:2px;font-weight:bold}.lines th{padding:8px;color:#fff;background:#176b4d;border:1px solid #176b4d}.lines td{padding:8px;border:1px solid #cbd5e1}.right{text-align:right}.center{text-align:center}.total td{font-weight:bold;background:#edf7f2}.observation{margin-top:18px;padding:10px;border:1px solid #cbd5e1;min-height:55px}.signatures{width:100%;margin-top:45px}.signatures td{width:33.33%;text-align:center;height:70px;vertical-align:top}.footer{margin-top:25px;padding-top:8px;border-top:1px solid #d8dee8;color:#64748b;text-align:center;font-size:9px}@media screen{body{padding:16px;background:#e5e7eb}.sheet{box-shadow:0 4px 20px rgba(15,23,42,.18)}}@media print{body{background:#fff}.actions{display:none}.sheet{width:auto;min-height:auto;margin:0;padding:0;box-shadow:none}}
</style>
</head>
<body class="{{ $pdfMode ? 'pdf-mode' : '' }}">
@unless($pdfMode)<div class="actions"><a href="{{ route('entree-caisses.index') }}">Retour</a><a href="{{ route('entree-caisses.pdf', $entree->id) }}">Télécharger PDF</a><button onclick="window.print()">Imprimer</button></div>@endunless
<div class="sheet">
<div class="header">@if($logoData)<img class="logo" src="{{ $logoData }}" alt="Logo">@endif<div class="company">{{ $entreprise?->nom_entreprise ?? 'Entreprise' }}</div>@if($entreprise?->slogan)<div class="slogan">{{ $entreprise->slogan }}</div>@endif<div class="contact">{{ $entreprise?->adresse }} @if($entreprise?->telephone) — Tél. {{ $entreprise->telephone }} @endif</div></div>
<h1>Bon d’entrée</h1><div class="number">N° {{ $entree->numero }}</div>
<table class="meta"><tr><td><span class="label">Date</span><span class="value">{{ \Carbon\Carbon::parse($entree->date)->format('d/m/Y') }}</span></td><td><span class="label">Statut</span><span class="value">{{ $entree->statut }}</span></td></tr><tr><td><span class="label">Monnaie</span><span class="value">{{ $entree->monnaie }}</span></td><td><span class="label">Créé par</span><span class="value">{{ trim(($entree->user?->prenom ?? '').' '.($entree->user?->nom ?? '')) ?: '—' }}</span></td></tr><tr><td colspan="2"><span class="label">Motif</span><span class="value">{{ $entree->motif }}</span></td></tr></table>
<table class="lines"><thead><tr><th>Désignation</th><th>Quantité</th><th>Prix unitaire</th><th>Montant</th></tr></thead><tbody>
@forelse($entree->lignes as $ligne)<tr><td>{{ $ligne->designation }}</td><td class="center">{{ number_format($ligne->quantite,2,',',' ') }}</td><td class="right">{{ number_format($ligne->prix_unitaire,2,',',' ') }} {{ $entree->monnaie }}</td><td class="right">{{ number_format($ligne->montant,2,',',' ') }} {{ $entree->monnaie }}</td></tr>@empty<tr><td colspan="4" class="center">Aucune ligne détaillée.</td></tr>@endforelse
<tr class="total"><td colspan="3" class="right">TOTAL DU BON</td><td class="right">{{ number_format($entree->montant,2,',',' ') }} {{ $entree->monnaie }}</td></tr></tbody></table>
<div class="observation"><span class="label">Observation</span><br>{{ $entree->observation ?: '—' }}</div>
<table class="signatures"><tr><td>Le déposant<br><br><br>____________________</td><td>Le caissier<br><br><br>____________________</td><td>La direction<br><br><br>____________________</td></tr></table>
<div class="footer">Document généré le {{ now()->format('d/m/Y à H:i') }}</div>
</div></body></html>
