@extends('layouts.app')
@section('title', 'Suivi et alertes comptables')
@section('content')
<div class="container-fluid py-4 px-lg-4">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><span class="text-uppercase text-muted small fw-bold">Paramètres · Sécurité</span><h3 class="mb-1"><i class="bi bi-shield-check me-2"></i>Suivi et alertes comptables</h3><p class="text-muted mb-0">Surveillance des suppressions, restaurations et actions sensibles.</p></div><div class="d-flex gap-2">@if($statistics['total'] > 0)<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalViderAudit"><i class="bi bi-trash3-fill me-1"></i>Vider l’audit</button>@endif<a href="{{ route('corbeille.index') }}" class="btn btn-outline-danger"><i class="bi bi-trash3 me-1"></i>Corbeille</a><a href="{{ route('parametres.parametre') }}" class="btn btn-outline-secondary">Retour</a></div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="row g-3 mb-4">@foreach([['Actions enregistrées',$statistics['total'],'activity','primary'],["Aujourd’hui",$statistics['aujourdhui'],'calendar-check','info'],['Documents validés supprimés',$statistics['documents_valides'],'exclamation-triangle','danger'],['Cascades contrôlées',$statistics['cascades'],'diagram-3','warning'],['Restaurations',$statistics['restaurations'],'arrow-counterclockwise','success'],['Suppressions définitives',$statistics['definitives'],'shield-exclamation','dark']] as [$label,$value,$icon,$color])<div class="col-6 col-xl-2"><div class="card border-0 shadow-sm h-100"><div class="card-body"><i class="bi bi-{{ $icon }} text-{{ $color }} fs-4"></i><div class="text-muted small mt-2">{{ $label }}</div><div class="fs-3 fw-bold">{{ $value }}</div></div></div></div>@endforeach</div>
    @if($statistics['documents_valides'] || $statistics['definitives'])<div class="alert alert-warning d-flex gap-3"><i class="bi bi-bell-fill fs-4"></i><div><strong>Signalement de sécurité</strong><div>{{ $statistics['documents_valides'] }} suppression(s) de document validé et {{ $statistics['definitives'] }} suppression(s) définitive(s) enregistrée(s).</div></div></div>@endif
    <form method="GET" class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-3"><label class="form-label">Action</label><select name="action" class="form-select"><option value="">Toutes</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(request('action')===$action)>{{ str_replace('_',' ',$action) }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Module</label><select name="module" class="form-select"><option value="">Tous</option>@foreach($modules as $module)<option value="{{ $module }}" @selected(request('module')===$module)>{{ class_basename($module) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Utilisateur</label><select name="user_id" class="form-select"><option value="">Tous</option>@foreach($users as $utilisateur)<option value="{{ $utilisateur->id }}" @selected((string)request('user_id')===(string)$utilisateur->id)>{{ $utilisateur->nom }} {{ $utilisateur->prenom }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Du</label><input type="date" name="date_debut" value="{{ request('date_debut') }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Au</label><input type="date" name="date_fin" value="{{ request('date_fin') }}" class="form-control"></div><div class="col-12 text-end"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Filtrer</button></div></div></form>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-dark"><tr><th>Date</th><th>Niveau</th><th>Action</th><th>Document</th><th>Référence</th><th>Utilisateur</th><th>Motif</th><th>IP</th></tr></thead><tbody>@forelse($audits as $audit)@php $alerte=in_array($audit->action,['suppression_document_valide','suppression_definitive']); @endphp<tr class="{{ $alerte?'table-warning':'' }}"><td class="text-nowrap">{{ $audit->created_at?->format('d/m/Y H:i:s') }}</td><td><span class="badge bg-{{ $alerte?'danger':'secondary' }}">{{ $alerte?'Alerte':'Information' }}</span></td><td>{{ str_replace('_',' ',$audit->action) }}</td><td>{{ class_basename($audit->model_type) }} #{{ $audit->model_id }}</td><td>{{ $audit->reference_document ?: '—' }}</td><td>{{ $audit->user?->nom }} {{ $audit->user?->prenom }}</td><td>{{ \Illuminate\Support\Str::limit($audit->motif,70) ?: '—' }}</td><td>{{ $audit->adresse_ip ?: '—' }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">Aucune activité d’audit.</td></tr>@endforelse</tbody></table></div>@if($audits->hasPages())<div class="card-footer bg-white">{{ $audits->links() }}</div>@endif</div>

    @if($statistics['total'] > 0)<div class="modal fade" id="modalViderAudit" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('parametres.audit.empty') }}">@csrf @method('DELETE')<div class="modal-header"><h5 class="modal-title"><i class="bi bi-exclamation-triangle-fill text-danger me-2"></i>Vider le journal d’audit</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button></div><div class="modal-body"><div class="alert alert-danger">Les {{ $statistics['total'] }} traces d’audit seront supprimées définitivement. Cette action est irréversible et ne supprime aucun document comptable.</div><div class="form-check mb-3"><input type="checkbox" name="confirmation" value="1" class="form-check-input" id="confirmationAudit" required><label class="form-check-label" for="confirmationAudit">Je confirme la suppression de toutes les traces d’audit.</label></div><label class="form-label">Saisissez <strong>VIDER LE JOURNAL D’AUDIT</strong></label><input type="text" name="phrase_confirmation" class="form-control" autocomplete="off" required></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button><button class="btn btn-danger"><i class="bi bi-trash3-fill me-1"></i>Vider définitivement</button></div></form></div></div></div>@endif
</div>
@endsection
